// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:home-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qmcA12X5QwV80GiQig8i/bfjOcbHx4XqXyOh4rn4H/ylFS2Ro4X.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["mRNjGIeHo", "KE_vVSixA"];
var serializationHash = "framer-AwHsY";
var variantClassNames = {
	KE_vVSixA: "framer-v-u0ys3h",
	mRNjGIeHo: "framer-v-qqtja7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "mRNjGIeHo",
	Phone: "KE_vVSixA",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "mRNjGIeHo",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "mRNjGIeHo",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={{
							webPageId: "augiA20Il",
						}}
						motionChild={true}
						nodeId={"mRNjGIeHo"}
						openInNewTab={false}
						scopeId={"ylFS2Ro4X"}
					>
						<Image
							{...restProps}
							{...gestureHandlers}
							as={"a"}
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 99.5,
								intrinsicWidth: 512,
								loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
								pixelHeight: 199,
								pixelWidth: 1024,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199",
								srcSet:
									"https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199 512w,https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?width=1024&height=199 1024w",
							}}
							className={`${cx(scopingClassNames, "framer-qqtja7", className, classNames)} framer-7aqzwn`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"mRNjGIeHo"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									KE_vVSixA: {
										"data-framer-name": "Phone",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-AwHsY.framer-7aqzwn, .framer-AwHsY .framer-7aqzwn { display: block; }",
	".framer-AwHsY.framer-qqtja7 { height: 75px; overflow: visible; position: relative; text-decoration: none; width: 386px; }",
	".framer-AwHsY.framer-v-u0ys3h.framer-qqtja7 { aspect-ratio: 5.1457286432160805 / 1; height: var(--framer-aspect-ratio-supported, 45px); width: 228px; }",
];
var FramerylFS2Ro4X = withCSS(Component, css, "framer-AwHsY");
var stdin_default = FramerylFS2Ro4X;
FramerylFS2Ro4X.displayName = "Home Button";
FramerylFS2Ro4X.defaultProps = {
	height: 75,
	width: 386,
};
addPropertyControls(FramerylFS2Ro4X, {
	variant: {
		options: ["mRNjGIeHo", "KE_vVSixA"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerylFS2Ro4X,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:home-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KE_vVSixA",
	"2xl": "mRNjGIeHo",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HomeButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var home_button_default = ComponentWithRoot;
export { home_button_default as default };
