// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:beyond-dentistry-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/i4T7KkgUXISDm2tiH4to/JSa0kL3GacvegluF5znD/kIWKY4Jj5.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-75C0H";
var variantClassNames = {
	EbgGpKJ_Z: "framer-v-p58oad",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "EbgGpKJ_Z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-p58oad",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"EbgGpKJ_Z"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1v6c0ly"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"P96qcOShL"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "50px",
									}}
								>
									{"Beyon dentistry,"}
								</motion.p>
								<motion.p
									style={{
										"--framer-font-size": "50px",
									}}
								>
									{"Unique patient experience"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-1dfzycg"}
							layoutDependency={layoutDependency}
							layoutId={"qGPQxSOCi"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-v0m2aa"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Lpu_gSp3y"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "17px",
										}}
									>
										{"Using Innovative Technology"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-15sm2jb"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"NS9uKAIYK"}
								style={{
									"--extracted-2gxw0f":
										"var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71))",
									"--extracted-r6o4lv":
										"var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate1}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "12px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71)))",
										}}
									>
										{
											"All our treatment rooms are furnished with state of the art "
										}
									</motion.p>
									<motion.p
										style={{
											"--framer-font-size": "12px",
											"--framer-text-color":
												"var(--extracted-2gxw0f, var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71)))",
										}}
									>
										{"equipment and maintained at the highest standards."}
									</motion.p>
								</React.Fragment>
							</RichText>
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 3024.5,
									intrinsicWidth: 2016.5,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 816) -
											593 +
											457 -
											369,
									),
									pixelHeight: 6049,
									pixelWidth: 4033,
									sizes: "356px",
									src: "https://framerusercontent.com/images/RWd12iDIDMNNwZDKDIUx208oM.jpg?scale-down-to=4096&width=4033&height=6049",
									srcSet:
										"https://framerusercontent.com/images/RWd12iDIDMNNwZDKDIUx208oM.jpg?scale-down-to=1024&width=4033&height=6049 682w,https://framerusercontent.com/images/RWd12iDIDMNNwZDKDIUx208oM.jpg?scale-down-to=2048&width=4033&height=6049 1365w,https://framerusercontent.com/images/RWd12iDIDMNNwZDKDIUx208oM.jpg?scale-down-to=4096&width=4033&height=6049 2730w,https://framerusercontent.com/images/RWd12iDIDMNNwZDKDIUx208oM.jpg?width=4033&height=6049 4033w",
								}}
								className={"framer-g4hffn"}
								data-framer-name={"Pexels-shvetsa-4586727"}
								layoutDependency={layoutDependency}
								layoutId={"lWdzjIKhD"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1j9r0zy"}
							layoutDependency={layoutDependency}
							layoutId={"ob3MTu0zg"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-xhbxfx"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"qr4bF02_b"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "17px",
										}}
									>
										{"In-House Dental Laboratory"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-dbprqj"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Wj8xcB8b_"}
								style={{
									"--extracted-2gxw0f":
										"var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71))",
									"--extracted-r6o4lv":
										"var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate1}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "12px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71)))",
										}}
									>
										{
											"All our smiles are custom made by our in-house master ceramist "
										}
									</motion.p>
									<motion.p
										style={{
											"--framer-font-size": "12px",
											"--framer-text-color":
												"var(--extracted-2gxw0f, var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71)))",
										}}
									>
										{"and team of dental technicians."}
									</motion.p>
								</React.Fragment>
							</RichText>
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 2964,
									intrinsicWidth: 1976,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 816) -
											593 +
											457 -
											368,
									),
									pixelHeight: 5928,
									pixelWidth: 3952,
									sizes: "356px",
									src: "https://framerusercontent.com/images/IEr8BhnL8q0LOJg0OJiM8VYfuIY.jpg?scale-down-to=4096&width=3952&height=5928",
									srcSet:
										"https://framerusercontent.com/images/IEr8BhnL8q0LOJg0OJiM8VYfuIY.jpg?scale-down-to=1024&width=3952&height=5928 682w,https://framerusercontent.com/images/IEr8BhnL8q0LOJg0OJiM8VYfuIY.jpg?scale-down-to=2048&width=3952&height=5928 1365w,https://framerusercontent.com/images/IEr8BhnL8q0LOJg0OJiM8VYfuIY.jpg?scale-down-to=4096&width=3952&height=5928 2730w,https://framerusercontent.com/images/IEr8BhnL8q0LOJg0OJiM8VYfuIY.jpg?width=3952&height=5928 3952w",
								}}
								className={"framer-1uuleco"}
								data-framer-name={"Pexels-cottonbro-6502306"}
								layoutDependency={layoutDependency}
								layoutId={"kqTLQn2WC"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							/>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1hl72cr"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"WYMyyPqon"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
									}}
								>
									{"In-House Dental Laboratory"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-axzlvf"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"n0AoPCixF"}
							style={{
								"--extracted-2gxw0f":
									"var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71))",
								"--extracted-r6o4lv":
									"var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "12px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71)))",
									}}
								>
									{"Patients enjoy the luxury of personal concierge services "}
								</motion.p>
								<motion.p
									style={{
										"--framer-font-size": "12px",
										"--framer-text-color":
											"var(--extracted-2gxw0f, var(--token-5d0298d3-2986-4c49-bcf4-b8e1782ac105, rgb(71, 71, 71)))",
									}}
								>
									{"throughout their dental treatment."}
								</motion.p>
							</React.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 1824,
								intrinsicWidth: 2736,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 816) -
										498,
								),
								pixelHeight: 3648,
								pixelWidth: 5472,
								sizes: "356px",
								src: "https://framerusercontent.com/images/9vtk8kynKm8UW318CYiNVX2w.jpg?scale-down-to=4096&width=5472&height=3648",
								srcSet:
									"https://framerusercontent.com/images/9vtk8kynKm8UW318CYiNVX2w.jpg?scale-down-to=512&width=5472&height=3648 512w,https://framerusercontent.com/images/9vtk8kynKm8UW318CYiNVX2w.jpg?scale-down-to=1024&width=5472&height=3648 1024w,https://framerusercontent.com/images/9vtk8kynKm8UW318CYiNVX2w.jpg?scale-down-to=2048&width=5472&height=3648 2048w,https://framerusercontent.com/images/9vtk8kynKm8UW318CYiNVX2w.jpg?scale-down-to=4096&width=5472&height=3648 4096w,https://framerusercontent.com/images/9vtk8kynKm8UW318CYiNVX2w.jpg?width=5472&height=3648 5472w",
							}}
							className={"framer-ovxqku"}
							data-framer-name={"Pexels-andre-furtado-43594-1429395"}
							layoutDependency={layoutDependency}
							layoutId={"ZMK1n7tEN"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-75C0H.framer-j947mw, .framer-75C0H .framer-j947mw { display: block; }",
	".framer-75C0H.framer-p58oad { height: 816px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-75C0H .framer-1v6c0ly { flex: none; height: 180px; left: 242px; position: absolute; top: 44px; white-space: pre-wrap; width: 754px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-75C0H .framer-1dfzycg { bottom: 136px; flex: none; height: 457px; left: 239px; overflow: var(--overflow-clip-fallback, clip); position: absolute; width: 397px; }",
	".framer-75C0H .framer-v0m2aa, .framer-75C0H .framer-xhbxfx { flex: none; height: auto; left: 16px; position: absolute; top: 7px; white-space: pre; width: auto; }",
	".framer-75C0H .framer-15sm2jb { flex: none; height: auto; left: 46%; position: absolute; top: 38px; white-space: pre; width: auto; }",
	".framer-75C0H .framer-g4hffn { bottom: 13px; flex: none; height: 356px; left: calc(50.00000000000002% - 356px / 2); overflow: visible; position: absolute; width: 356px; }",
	".framer-75C0H .framer-1j9r0zy { bottom: 136px; flex: none; height: 457px; left: calc(50.5294117647059% - 414px / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; width: 414px; }",
	".framer-75C0H .framer-dbprqj { flex: none; height: auto; left: 51%; position: absolute; top: 40px; white-space: pre; width: auto; }",
	".framer-75C0H .framer-1uuleco { bottom: 12px; flex: none; height: 356px; left: calc(50.00000000000002% - 356px / 2); overflow: visible; position: absolute; width: 356px; }",
	".framer-75C0H .framer-1hl72cr { flex: none; height: auto; left: 1315px; position: absolute; top: 200px; white-space: pre; width: auto; }",
	".framer-75C0H .framer-axzlvf { flex: none; height: auto; left: 1317px; position: absolute; top: 229px; white-space: pre; width: auto; }",
	".framer-75C0H .framer-ovxqku { bottom: 142px; flex: none; height: 356px; left: 1105px; overflow: visible; position: absolute; width: 356px; }",
];
var FramerkIWKY4Jj5 = withCSS(Component, css, "framer-75C0H");
var stdin_default = FramerkIWKY4Jj5;
FramerkIWKY4Jj5.displayName = "Beyond Dentistry Desktop";
FramerkIWKY4Jj5.defaultProps = {
	height: 816,
	width: 1700,
};
addFonts(
	FramerkIWKY4Jj5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:beyond-dentistry-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BeyondDentistryDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var beyond_dentistry_desktop_default = ComponentWithRoot;
export { beyond_dentistry_desktop_default as default };
