// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-TEG36AA5.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:contact-book-your-dental-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/x1PxszsJtzaqV7bWy2OF/I2o4t3gNxZMkp1mAc8Cc/dhDmEMX_p.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-ItP1g";
var variantClassNames = {
	sDpulxEZK: "framer-v-11fl02i",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "sDpulxEZK",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-11fl02i",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"sDpulxEZK"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 507,
								intrinsicWidth: 501,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 1176) -
										795,
								),
								pixelHeight: 1014,
								pixelWidth: 1002,
								sizes: "561px",
								src: "https://framerusercontent.com/images/yeBsz6T3iHf0jm5wZjUafTTJeg.png?scale-down-to=512&width=1002&height=1014",
								srcSet:
									"https://framerusercontent.com/images/yeBsz6T3iHf0jm5wZjUafTTJeg.png?width=1002&height=1014 1002w",
							}}
							className={"framer-a7de6r"}
							data-framer-name={"Screenshot 2568-10-28 at 19.06.37"}
							layoutDependency={layoutDependency}
							layoutId={"UeRIeGAiZ"}
						/>
						<motion.div
							className={"framer-p8mqvt"}
							layoutDependency={layoutDependency}
							layoutId={"jLTJOlvCm"}
							style={{
								backgroundColor: "rgb(237, 200, 96)",
								borderBottomLeftRadius: 39,
								borderBottomRightRadius: 39,
								borderTopLeftRadius: 39,
								borderTopRightRadius: 39,
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-nw2173"}
								fonts={["GF;Actor-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"TcC3yxzjd"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate1}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7QWN0b3ItcmVndWxhcg==",
											"--framer-font-family":
												'"Actor", "Actor Placeholder", sans-serif',
											"--framer-font-size": "17px",
										}}
									>
										{"Request an appointment"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 483,
								intrinsicWidth: 491,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 1176) -
										795,
								),
								pixelHeight: 966,
								pixelWidth: 982,
								sizes: "577px",
								src: "https://framerusercontent.com/images/9SHLuGoVvdaLa6WnH39EOWsL48.png?scale-down-to=512&width=982&height=966",
								srcSet:
									"https://framerusercontent.com/images/9SHLuGoVvdaLa6WnH39EOWsL48.png?scale-down-to=512&width=982&height=966 512w,https://framerusercontent.com/images/9SHLuGoVvdaLa6WnH39EOWsL48.png?width=982&height=966 982w",
							}}
							className={"framer-1r1vco4"}
							data-framer-name={"Screenshot 2568-10-28 at 19.07.39"}
							layoutDependency={layoutDependency}
							layoutId={"DO2QIFJHw"}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-18yrk3p"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"Jb8YS31fi"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h3
									className={"framer-styles-preset-1rj9tbl"}
									data-styles-preset={"Iy4zURptt"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									{"Book Your Dental "}
									<motion.br />
									{"Appointment Online with "}
									<motion.br />
									{"Ease"}
								</motion.h3>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ItP1g.framer-v4jjbd, .framer-ItP1g .framer-v4jjbd { display: block; }",
	".framer-ItP1g.framer-11fl02i { height: 1176px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-ItP1g .framer-a7de6r { bottom: 222px; flex: none; height: 573px; left: 903px; overflow: visible; position: absolute; width: 561px; }",
	".framer-ItP1g .framer-p8mqvt { bottom: 124px; flex: none; height: 45px; left: 239px; overflow: var(--overflow-clip-fallback, clip); position: absolute; width: 232px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ItP1g .framer-nw2173 { flex: none; height: auto; left: 50%; position: absolute; top: 49%; white-space: pre; width: auto; }",
	".framer-ItP1g .framer-1r1vco4 { aspect-ratio: 1.0165631469979297 / 1; bottom: 228px; flex: none; height: var(--framer-aspect-ratio-supported, 568px); left: 151px; overflow: visible; position: absolute; width: 577px; }",
	".framer-ItP1g .framer-18yrk3p { flex: none; height: 215px; left: 151px; position: absolute; top: 74px; white-space: pre-wrap; width: 608px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	...css,
];
var FramerdhDmEMX_p = withCSS(Component, css2, "framer-ItP1g");
var stdin_default = FramerdhDmEMX_p;
FramerdhDmEMX_p.displayName = "Contact Book Your Dental Desktop";
FramerdhDmEMX_p.defaultProps = {
	height: 1176,
	width: 1700,
};
addFonts(
	FramerdhDmEMX_p,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Actor",
					source: "google",
					style: "normal",
					uiFamilyName: "Actor",
					url: "https://fonts.gstatic.com/s/actor/v18/wEOzEBbCkc5cO3ehXygtUMIO.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:contact-book-your-dental-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactBookYourDentalDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var contact_book_your_dental_desktop_default = ComponentWithRoot;
export { contact_book_your_dental_desktop_default as default };
