// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:contact-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xR2dm1rctXs5t5S0aG0C/KUXIcy13s6q2v8DLx9FU/lEwj7Y9KX.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-IN9Jz";
var variantClassNames = {
	lQjSLbLZ6: "framer-v-hjyo03",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "lQjSLbLZ6",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							fit: "fill",
							intrinsicHeight: 1102,
							intrinsicWidth: 642,
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 2204,
							pixelWidth: 1284,
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/kuPr6FrwFeYJh3glo4kzLmsxz0.jpg?scale-down-to=2048&width=1284&height=2204",
							srcSet:
								"https://framerusercontent.com/images/kuPr6FrwFeYJh3glo4kzLmsxz0.jpg?scale-down-to=1024&width=1284&height=2204 596w,https://framerusercontent.com/images/kuPr6FrwFeYJh3glo4kzLmsxz0.jpg?scale-down-to=2048&width=1284&height=2204 1193w,https://framerusercontent.com/images/kuPr6FrwFeYJh3glo4kzLmsxz0.jpg?width=1284&height=2204 1284w",
						}}
						className={cx(
							scopingClassNames,
							"framer-hjyo03",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"lQjSLbLZ6"}
						ref={refBinding}
						style={{
							...style,
						}}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IN9Jz.framer-w8bbzo, .framer-IN9Jz .framer-w8bbzo { display: block; }",
	".framer-IN9Jz.framer-hjyo03 { height: 670px; overflow: visible; position: relative; width: 390px; }",
];
var FramerlEwj7Y9KX = withCSS(Component, css, "framer-IN9Jz");
var stdin_default = FramerlEwj7Y9KX;
FramerlEwj7Y9KX.displayName = "Contact Section";
FramerlEwj7Y9KX.defaultProps = {
	height: 669.5,
	width: 390,
};
addFonts(
	FramerlEwj7Y9KX,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:contact-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var contact_section_default = ComponentWithRoot;
export { contact_section_default as default };
