// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:doctors-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/LxERqSgMhTVf4LWhxgL6/lzO1cynTb2GdyAW7e1QZ/RePwjfOfZ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/wJk8rUZMHid8TWc2tEog/b4207DzgsRsIkVn7HiKA/I48r6qbOs.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	'.framer-bHlDw .framer-styles-preset-ucyj0j:not(.rich-text-wrapper), .framer-bHlDw .framer-styles-preset-ucyj0j.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 29px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className = "framer-bHlDw";

// /:https://framerusercontent.com/modules/LxERqSgMhTVf4LWhxgL6/lzO1cynTb2GdyAW7e1QZ/RePwjfOfZ.js
var serializationHash = "framer-w4xeo";
var variantClassNames = {
	HxOwRXesw: "framer-v-17406j4",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "HxOwRXesw",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17406j4",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"HxOwRXesw"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 3e3,
								intrinsicWidth: 2e3,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 1177) -
										327,
								),
								pixelHeight: 6e3,
								pixelWidth: 4e3,
								sizes: "236px",
								src: "https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=4096&width=4000&height=6000",
								srcSet:
									"https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=1024&width=4000&height=6000 682w,https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=2048&width=4000&height=6000 1365w,https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=4096&width=4000&height=6000 2730w,https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?width=4000&height=6000 4000w",
							}}
							className={"framer-14nt7gl"}
							data-framer-name={"Pexels-shkrabaanthony-5214995"}
							layoutDependency={layoutDependency}
							layoutId={"i7PWZifY7"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 2540,
								intrinsicWidth: 1695.5,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 1177) -
										684,
								),
								pixelHeight: 5080,
								pixelWidth: 3391,
								sizes: "236px",
								src: "https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=4096&width=3391&height=5080",
								srcSet:
									"https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=1024&width=3391&height=5080 683w,https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=2048&width=3391&height=5080 1367w,https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=4096&width=3391&height=5080 2734w,https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?width=3391&height=5080 3391w",
							}}
							className={"framer-aj5wff"}
							data-framer-name={"Pexels-pavel-danilyuk-8442615"}
							layoutDependency={layoutDependency}
							layoutId={"Q8Uc85T7S"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 2250,
								intrinsicWidth: 1633,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 136,
								),
								pixelHeight: 4500,
								pixelWidth: 3266,
								sizes: "236px",
								src: "https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=4096&width=3266&height=4500",
								srcSet:
									"https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=1024&width=3266&height=4500 743w,https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=2048&width=3266&height=4500 1486w,https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=4096&width=3266&height=4500 2972w,https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?width=3266&height=4500 3266w",
							}}
							className={"framer-131wkvt"}
							data-framer-name={"Pexels-havanna-34457092"}
							layoutDependency={layoutDependency}
							layoutId={"kPrZy3JxQ"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1hwm3m2"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"vwF2m8fUW"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-ucyj0j"}
									data-styles-preset={"I48r6qbOs"}
								>
									{"Your smile's best friends, Our doctors"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-w4xeo.framer-1fohjuj, .framer-w4xeo .framer-1fohjuj { display: block; }",
	".framer-w4xeo.framer-17406j4 { height: 1177px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 390px; }",
	".framer-w4xeo .framer-14nt7gl { bottom: 0px; flex: none; height: 327px; left: calc(50.00000000000002% - 236px / 2); overflow: visible; position: absolute; width: 236px; }",
	".framer-w4xeo .framer-aj5wff { bottom: 357px; flex: none; height: 327px; left: calc(50.00000000000002% - 236px / 2); overflow: visible; position: absolute; width: 236px; }",
	".framer-w4xeo .framer-131wkvt { flex: none; height: 327px; left: calc(50.00000000000002% - 236px / 2); overflow: visible; position: absolute; top: 136px; width: 236px; }",
	".framer-w4xeo .framer-1hwm3m2 { flex: none; height: 90px; left: calc(50.00000000000002% - 290px / 2); position: absolute; top: 30px; white-space: pre-wrap; width: 290px; word-break: break-word; word-wrap: break-word; }",
	...css,
];
var FramerRePwjfOfZ = withCSS(Component, css2, "framer-w4xeo");
var stdin_default = FramerRePwjfOfZ;
FramerRePwjfOfZ.displayName = "Doctors Mobile";
FramerRePwjfOfZ.defaultProps = {
	height: 1177,
	width: 390,
};
addFonts(
	FramerRePwjfOfZ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:doctors-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DoctorsMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var doctors_mobile_default = ComponentWithRoot;
export { doctors_mobile_default as default };
