// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-TRIO4S56.js";
import { stdin_default as stdin_default5 } from "./chunks/chunk-D32AEMAK.js";
import { Ticker } from "./chunks/chunk-I5OAE6PV.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-ZYRXVZ6Z.js";
import { stdin_default } from "./chunks/chunk-SJKXXIWI.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-P4D4OB5H.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:featured-in-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/IGSWImuNOjqPNiEi3TpL/0XpoRzEwIH3nCoMa3KxV/kjtUFUX5Y.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ForbesFonts = getFonts(stdin_default);
var NetflixLogoFonts = getFonts(stdin_default4);
var TimeFonts = getFonts(stdin_default2);
var ThePostLogoFonts = getFonts(stdin_default3);
var IncFonts = getFonts(stdin_default5);
var TickerFonts = getFonts(Ticker);
var serializationHash = "framer-QaaTd";
var variantClassNames = {
	quYryd9zx: "framer-v-muw5ls",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "quYryd9zx",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-muw5ls",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"quYryd9zx"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-hyfh5x-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"rcWIuGIQC-container"}
								nodeId={"rcWIuGIQC"}
								rendersWithMotion={true}
								scopeId={"kjtUFUX5Y"}
							>
								<Ticker
									alignment={"center"}
									direction={"left"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={133}
									height={"100%"}
									hoverFactor={1}
									id={"rcWIuGIQC"}
									layoutId={"rcWIuGIQC"}
									padding={122}
									paddingBottom={122}
									paddingLeft={122}
									paddingPerSide={false}
									paddingRight={122}
									paddingTop={122}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<ComponentViewportProvider height={29} width={"109px"}>
											<SmartComponentScopedContainer
												className={"framer-18wxd4y-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"Bgvm8ggu7-container"}
												nodeId={"Bgvm8ggu7"}
												rendersWithMotion={true}
												scopeId={"kjtUFUX5Y"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													id: "Bgvm8ggu7",
													layoutId: "Bgvm8ggu7",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={61} width={"130px"}>
											<SmartComponentScopedContainer
												className={"framer-ylot4b-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"OQVy5LNPx-container"}
												nodeId={"OQVy5LNPx"}
												rendersWithMotion={true}
												scopeId={"kjtUFUX5Y"}
											>
												{_jsx(stdin_default4, {
													height: "100%",
													id: "OQVy5LNPx",
													layoutId: "OQVy5LNPx",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={38} width={"121px"}>
											<SmartComponentScopedContainer
												className={"framer-1b4a32u-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"O4W53Ue4l-container"}
												nodeId={"O4W53Ue4l"}
												rendersWithMotion={true}
												scopeId={"kjtUFUX5Y"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "O4W53Ue4l",
													layoutId: "O4W53Ue4l",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={44} width={"279px"}>
											<SmartComponentScopedContainer
												className={"framer-w49jmz-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"rQenVsLcc-container"}
												nodeId={"rQenVsLcc"}
												rendersWithMotion={true}
												scopeId={"kjtUFUX5Y"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "rQenVsLcc",
													layoutId: "rQenVsLcc",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={44} width={"122px"}>
											<SmartComponentScopedContainer
												className={"framer-17ybpdb-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"VFbz10weH-container"}
												nodeId={"VFbz10weH"}
												rendersWithMotion={true}
												scopeId={"kjtUFUX5Y"}
											>
												{_jsx(stdin_default5, {
													height: "100%",
													id: "VFbz10weH",
													layoutId: "VFbz10weH",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									speed={50}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QaaTd.framer-1y05cfs, .framer-QaaTd .framer-1y05cfs { display: block; }",
	".framer-QaaTd.framer-muw5ls { height: 148px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1608px; }",
	".framer-QaaTd .framer-hyfh5x-container { bottom: -11px; flex: none; left: 0px; position: absolute; right: 0px; top: -11px; }",
	".framer-QaaTd .framer-18wxd4y-container { height: 29px; position: relative; width: 109px; }",
	".framer-QaaTd .framer-ylot4b-container { height: 61px; position: relative; width: 130px; }",
	".framer-QaaTd .framer-1b4a32u-container { height: 38px; position: relative; width: 121px; }",
	".framer-QaaTd .framer-w49jmz-container { height: 44px; position: relative; width: 279px; }",
	".framer-QaaTd .framer-17ybpdb-container { height: 44px; position: relative; width: 122px; }",
];
var FramerkjtUFUX5Y = withCSS(Component, css, "framer-QaaTd");
var stdin_default6 = FramerkjtUFUX5Y;
FramerkjtUFUX5Y.displayName = "Featured in Desktop";
FramerkjtUFUX5Y.defaultProps = {
	height: 148,
	width: 1608,
};
addFonts(
	FramerkjtUFUX5Y,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ForbesFonts,
		...NetflixLogoFonts,
		...TimeFonts,
		...ThePostLogoFonts,
		...IncFonts,
		...TickerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:featured-in-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturedInDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var featured_in_desktop_default = ComponentWithRoot;
export { featured_in_desktop_default as default };
