// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-TRIO4S56.js";
import { stdin_default as stdin_default5 } from "./chunks/chunk-D32AEMAK.js";
import { Ticker } from "./chunks/chunk-I5OAE6PV.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-ZYRXVZ6Z.js";
import { stdin_default } from "./chunks/chunk-SJKXXIWI.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-P4D4OB5H.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:featured-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qWmozRWsPwMWeP8cB0Xk/Sof2HQHLmRxnIan5HuOb/spwgBRsLq.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var IncFonts = getFonts(stdin_default5);
var ThePostLogoFonts = getFonts(stdin_default3);
var TimeFonts = getFonts(stdin_default2);
var NetflixLogoFonts = getFonts(stdin_default4);
var ForbesFonts = getFonts(stdin_default);
var TickerFonts = getFonts(Ticker);
var serializationHash = "framer-cTUdF";
var variantClassNames = {
	y5UAYb_QJ: "framer-v-3u4snb",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "y5UAYb_QJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3u4snb",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"y5UAYb_QJ"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-17ggf33-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"g5gUqHzUe-container"}
								nodeId={"g5gUqHzUe"}
								rendersWithMotion={true}
								scopeId={"spwgBRsLq"}
							>
								<Ticker
									alignment={"center"}
									direction={"left"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={70}
									height={"100%"}
									hoverFactor={1}
									id={"g5gUqHzUe"}
									layoutId={"g5gUqHzUe"}
									padding={38}
									paddingBottom={38}
									paddingLeft={38}
									paddingPerSide={false}
									paddingRight={38}
									paddingTop={38}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<ComponentViewportProvider height={44} width={"122px"}>
											<SmartComponentScopedContainer
												className={"framer-fu770e-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"TNi9WmbAR-container"}
												nodeId={"TNi9WmbAR"}
												rendersWithMotion={true}
												scopeId={"spwgBRsLq"}
											>
												{_jsx(stdin_default5, {
													height: "100%",
													id: "TNi9WmbAR",
													layoutId: "TNi9WmbAR",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={44} width={"279px"}>
											<SmartComponentScopedContainer
												className={"framer-1nycizz-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"VqTK88xtF-container"}
												nodeId={"VqTK88xtF"}
												rendersWithMotion={true}
												scopeId={"spwgBRsLq"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "VqTK88xtF",
													layoutId: "VqTK88xtF",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={38} width={"121px"}>
											<SmartComponentScopedContainer
												className={"framer-bsudk0-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"nF5E_Ah02-container"}
												nodeId={"nF5E_Ah02"}
												rendersWithMotion={true}
												scopeId={"spwgBRsLq"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "nF5E_Ah02",
													layoutId: "nF5E_Ah02",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={61} width={"130px"}>
											<SmartComponentScopedContainer
												className={"framer-9ukfdc-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"aNqaG3dgT-container"}
												nodeId={"aNqaG3dgT"}
												rendersWithMotion={true}
												scopeId={"spwgBRsLq"}
											>
												{_jsx(stdin_default4, {
													height: "100%",
													id: "aNqaG3dgT",
													layoutId: "aNqaG3dgT",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={29} width={"109px"}>
											<SmartComponentScopedContainer
												className={"framer-1im2zw3-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"x1LuAWewQ-container"}
												nodeId={"x1LuAWewQ"}
												rendersWithMotion={true}
												scopeId={"spwgBRsLq"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													id: "x1LuAWewQ",
													layoutId: "x1LuAWewQ",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									speed={50}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cTUdF.framer-e70nvd, .framer-cTUdF .framer-e70nvd { display: block; }",
	".framer-cTUdF.framer-3u4snb { height: 147px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 390px; }",
	".framer-cTUdF .framer-17ggf33-container { flex: none; height: 103px; left: 0px; position: absolute; right: 0px; top: calc(49.65986394557825% - 103px / 2); }",
	".framer-cTUdF .framer-fu770e-container { height: 44px; position: relative; width: 122px; }",
	".framer-cTUdF .framer-1nycizz-container { height: 44px; position: relative; width: 279px; }",
	".framer-cTUdF .framer-bsudk0-container { height: 38px; position: relative; width: 121px; }",
	".framer-cTUdF .framer-9ukfdc-container { height: 61px; position: relative; width: 130px; }",
	".framer-cTUdF .framer-1im2zw3-container { height: 29px; position: relative; width: 109px; }",
];
var FramerspwgBRsLq = withCSS(Component, css, "framer-cTUdF");
var stdin_default6 = FramerspwgBRsLq;
FramerspwgBRsLq.displayName = "Featured Mobile";
FramerspwgBRsLq.defaultProps = {
	height: 147,
	width: 390,
};
addFonts(
	FramerspwgBRsLq,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...IncFonts,
		...ThePostLogoFonts,
		...TimeFonts,
		...NetflixLogoFonts,
		...ForbesFonts,
		...TickerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:featured-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturedMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var featured_mobile_default = ComponentWithRoot;
export { featured_mobile_default as default };
