// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-X35YBW7T.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:footer-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/v6fra4U1GDgyEvSHGWmi/N7A7ZCzGJTyF1zPL1dZg/h0okHMX1X.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-5qfRT";
var variantClassNames = {
	hzlqk3pHq: "framer-v-3ic7r5",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "hzlqk3pHq",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3ic7r5",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"hzlqk3pHq"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(21, 20, 14)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-6f25e4"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"XAhkjb03f"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Contact"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-qbme22"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"UA5LAq30h"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Office Hours"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-fq2t8u"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ectSa92ie"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Social Media"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-fpp5bi"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ZSVpTl4bW"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Dental Services"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-3mecc9"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"WPoPRbY5h"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"About"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-s3bck5"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"XA1nNM5cc"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Remington Dental Care"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1a2iq91"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"tGPoW66vR"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Mon-Fri: 9am-7pm"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1txnahu"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"GPo5mcz4p"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Cleanings and Prevention"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-kfdot6"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"aK9J8WthQ"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Blog"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1j3k3d1"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"jSMeixsMi"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Glossary"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-mxa2g"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"rKBK5RJW2"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Privacy Policy"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1wiy5g8"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"kLH5SecfY"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Terms of Use"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-8ceutt"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"oz3N6S9q2"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Sitemap"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-b2u7nc"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"fbKb3suT2"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Costmetic Dentristry"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-gjw7l6"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"uVnWoBcm9"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Endodontics"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1kfo2j"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"y0SW7u78B"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"1938 27th St, Manhattan, NY 11294"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-129iew8"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"iMkNxI7Nw"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"P18386638239"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-jpbpm0"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"AJbVu2x1E"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"info@remingtondentalcare.com"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 71,
								intrinsicWidth: 249,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 101,
								),
								pixelHeight: 142,
								pixelWidth: 498,
								src: "https://framerusercontent.com/images/EijoCohOI3vv5s1lbbDG7p0hoE.png?width=498&height=142",
							}}
							className={"framer-1m2vwyj"}
							data-framer-name={"Screenshot 2568-10-28 at 19.21.38"}
							layoutDependency={layoutDependency}
							layoutId={"HPUsbiN60"}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 512,
								intrinsicWidth: 512,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 539) * 0.49907235621521356 -
											195.5),
								),
								pixelHeight: 1024,
								pixelWidth: 1024,
								sizes: "463px",
								src: "https://framerusercontent.com/images/qHw2UgDNQz9ORL5GhsCIDqys5Q.png?scale-down-to=512&width=1024&height=1024",
								srcSet:
									"https://framerusercontent.com/images/qHw2UgDNQz9ORL5GhsCIDqys5Q.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/qHw2UgDNQz9ORL5GhsCIDqys5Q.png?width=1024&height=1024 1024w",
							}}
							className={"framer-r2r0ly"}
							data-framer-name={"8A9C680C-EECE-4883-A3B1-919CF851625D"}
							layoutDependency={layoutDependency}
							layoutId={"HPingIeQu"}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5qfRT.framer-1hnmj0g, .framer-5qfRT .framer-1hnmj0g { display: block; }",
	".framer-5qfRT.framer-3ic7r5 { height: 539px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-5qfRT .framer-6f25e4 { flex: none; height: auto; left: 688px; position: absolute; top: 64px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-qbme22 { flex: none; height: auto; left: 920px; position: absolute; top: 64px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-fq2t8u { flex: none; height: auto; left: 1079px; position: absolute; top: 64px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-fpp5bi { flex: none; height: auto; left: 1253px; position: absolute; top: 64px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-3mecc9 { flex: none; height: auto; left: 1478px; position: absolute; top: 64px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-s3bck5 { flex: none; height: auto; left: 688px; position: absolute; top: 101px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-1a2iq91 { flex: none; height: auto; left: 920px; position: absolute; top: 101px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-1txnahu { flex: none; height: auto; left: 1253px; position: absolute; top: 101px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-kfdot6 { flex: none; height: auto; left: 1478px; position: absolute; top: 101px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-1j3k3d1 { flex: none; height: auto; left: 1478px; position: absolute; top: 136px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-mxa2g { flex: none; height: auto; left: 1478px; position: absolute; top: 171px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-1wiy5g8 { flex: none; height: auto; left: 1478px; position: absolute; top: 203px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-8ceutt { flex: none; height: auto; left: 1478px; position: absolute; top: 234px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-b2u7nc { flex: none; height: auto; left: 1253px; position: absolute; top: 136px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-gjw7l6 { flex: none; height: auto; left: 1253px; position: absolute; top: 171px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-1kfo2j { flex: none; height: auto; left: 47%; position: absolute; top: 136px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-129iew8 { flex: none; height: auto; left: 688px; position: absolute; top: 171px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-jpbpm0 { flex: none; height: auto; left: 46%; position: absolute; top: 206px; white-space: pre; width: auto; }",
	".framer-5qfRT .framer-1m2vwyj { aspect-ratio: 3.507042253521127 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); left: 1079px; overflow: visible; position: absolute; top: 101px; width: 139px; }",
	".framer-5qfRT .framer-r2r0ly { flex: none; height: 391px; left: 76px; overflow: visible; position: absolute; top: calc(49.90723562152136% - 391px / 2); width: 463px; }",
	...css,
];
var Framerh0okHMX1X = withCSS(Component, css2, "framer-5qfRT");
var stdin_default = Framerh0okHMX1X;
Framerh0okHMX1X.displayName = "Footer Desktop";
Framerh0okHMX1X.defaultProps = {
	height: 539,
	width: 1700,
};
addFonts(
	Framerh0okHMX1X,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_desktop_default = ComponentWithRoot;
export { footer_desktop_default as default };
