// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-X35YBW7T.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tGHgWO4knat6vRT7GJvw/oz6rzMIEpEcu5pBHosVc/GXKfRpBBO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-ODkgs";
var variantClassNames = {
	yiASFD2j7: "framer-v-1lsglbq",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "yiASFD2j7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1lsglbq",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"yiASFD2j7"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(21, 20, 14)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-v7wzog"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"u0itHSHnc"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Contact"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1fipvle"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"W0xLmfTvC"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Office Hours"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1unz67x"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"lekNyB5Wn"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Social Media"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1514eeu"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"usX9Rrymi"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"Dental Services"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1gq4cy"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"iEzMGvtUM"}
							style={{
								"--extracted-r6o4lv": "rgb(245, 245, 245)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "17px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(245, 245, 245))",
									}}
								>
									{"About"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1v8q7qb"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"WPGVkQjEL"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Remington Dental Care"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1t39bpf"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"vW8kzRVuB"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Mon-Fri: 9am-7pm"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-utmkdk"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"JK7Poq1ha"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Cleanings and Prevention"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-y9tdh1"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"t1MdMMOkG"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Blog"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-kqxs69"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"vRLe9leiP"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Glossary"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-qyhf2r"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"LvOwo7yH7"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Privacy Policy"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-xfyran"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"bnaKRFcaa"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Terms of Use"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1g2ej5n"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ArFq6TaYC"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Sitemap"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-e8t3wx"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"fLARZFNPk"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Costmetic Dentristry"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-146fny2"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"R8N7moP5J"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"Endodontics"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-r4s16b"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"iTgf1MgTz"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"1938 27th St, Manhattan, NY 11294"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-18vmc18"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"GjT4_Sk_7"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"P18386638239"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-7rdywl"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"nzyyEjxHD"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1swk920"}
									data-styles-preset={"GkVSJe_NB"}
								>
									{"info@remingtondentalcare.com"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 71,
								intrinsicWidth: 249,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 325,
								),
								pixelHeight: 142,
								pixelWidth: 498,
								src: "https://framerusercontent.com/images/EijoCohOI3vv5s1lbbDG7p0hoE.png?width=498&height=142",
							}}
							className={"framer-wnsoa6"}
							data-framer-name={"Screenshot 2568-10-28 at 19.21.38"}
							layoutDependency={layoutDependency}
							layoutId={"bimvSiCj8"}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ODkgs.framer-14cr445, .framer-ODkgs .framer-14cr445 { display: block; }",
	".framer-ODkgs.framer-1lsglbq { height: 812px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 390px; }",
	".framer-ODkgs .framer-v7wzog { flex: none; height: auto; left: 25px; position: absolute; top: 42px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1fipvle { flex: none; height: auto; left: 25px; position: absolute; top: 216px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1unz67x { flex: none; height: auto; left: 25px; position: absolute; top: 301px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1514eeu { flex: none; height: auto; left: 25px; position: absolute; top: 52%; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1gq4cy { bottom: 229px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1v8q7qb { flex: none; height: auto; left: 25px; position: absolute; top: 74px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1t39bpf { flex: none; height: auto; left: 25px; position: absolute; top: 248px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-utmkdk { bottom: 338px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-y9tdh1 { bottom: 193px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-kqxs69 { bottom: 166px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-qyhf2r { bottom: 139px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-xfyran { bottom: 112px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-1g2ej5n { bottom: 85px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-e8t3wx { bottom: 311px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-146fny2 { bottom: 284px; flex: none; height: auto; left: 25px; position: absolute; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-r4s16b { flex: none; height: auto; left: 25px; position: absolute; top: 101px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-18vmc18 { flex: none; height: auto; left: 25px; position: absolute; top: 128px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-7rdywl { flex: none; height: auto; left: 25px; position: absolute; top: 155px; white-space: pre; width: auto; }",
	".framer-ODkgs .framer-wnsoa6 { aspect-ratio: 3.507042253521127 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 56px); left: 17px; overflow: visible; position: absolute; top: 325px; width: 196px; }",
	...css,
];
var FramerGXKfRpBBO = withCSS(Component, css2, "framer-ODkgs");
var stdin_default = FramerGXKfRpBBO;
FramerGXKfRpBBO.displayName = "Footer";
FramerGXKfRpBBO.defaultProps = {
	height: 812,
	width: 390,
};
addFonts(
	FramerGXKfRpBBO,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_default = ComponentWithRoot;
export { footer_default as default };
