// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile Closed' | 'Mobile Open' | 'Variant 4' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-C65GIQBU.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-ZOKOWKTV.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:header-section-3
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/JrIm0yQPvGwwfjqLIyAM/OBhsNzBRUuEgh6aFShQZ/uIJgq8jjn.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MenuItemFonts = getFonts(stdin_default);
var PrimaryButtonFonts = getFonts(stdin_default2);
var cycleOrder = ["o4vq3rsib", "OrvQ15ubb", "FrgF7jG8i", "LLaZ1Y4wA"];
var serializationHash = "framer-6WJdQ";
var variantClassNames = {
	FrgF7jG8i: "framer-v-adczhb",
	LLaZ1Y4wA: "framer-v-y3y3n3",
	o4vq3rsib: "framer-v-ewcmmp",
	OrvQ15ubb: "framer-v-1fo9999",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mobile Closed": "OrvQ15ubb",
	"Mobile Open": "FrgF7jG8i",
	"Variant 4": "LLaZ1Y4wA",
	Desktop: "o4vq3rsib",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "o4vq3rsib",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "o4vq3rsib",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1u1ipsj = activeVariantCallback(async (...args) => {
		setVariant("FrgF7jG8i");
	});
	const sharedStyleClassNames = [];
	const isDisplayed = () => {
		if (baseVariant === "OrvQ15ubb") return false;
		return true;
	};
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed1 = () => {
		if (baseVariant === "FrgF7jG8i") return true;
		return false;
	};
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				{isDisplayed() && (
					<Transition value={transition1}>
						<motion.header
							{...restProps}
							{...gestureHandlers}
							className={cx(
								scopingClassNames,
								"framer-ewcmmp",
								className,
								classNames,
							)}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"o4vq3rsib"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								...style,
							}}
							variants={{
								FrgF7jG8i: {
									"--border-bottom-width": "1px",
									"--border-color": "rgb(255, 255, 255)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgb(255, 255, 255)",
								},
								LLaZ1Y4wA: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
							{...addPropertyOverrides(
								{
									FrgF7jG8i: {
										"data-border": true,
										"data-framer-name": "Mobile Open",
									},
									LLaZ1Y4wA: {
										"data-framer-name": "Variant 4",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1kjitb1"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"ifWcJikJN"}
							>
								<motion.div
									className={"framer-uj39id"}
									data-framer-name={"Logo"}
									layoutDependency={layoutDependency}
									layoutId={"gZ2ZD72D7"}
								>
									<motion.div
										className={"framer-12w9xve"}
										data-framer-name={"Mobile Menu Icon"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"bN1BIRL9g"}
										onTap={onTap1u1ipsj}
										style={{
											backgroundColor: "rgba(255, 255, 255, 0)",
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
										}}
										transformTemplate={transformTemplate1}
									>
										<motion.div
											className={"framer-gs4s1u"}
											data-framer-name={"Line"}
											layoutDependency={layoutDependency}
											layoutId={"my1pmhLKk"}
											style={{
												backgroundColor: "rgb(0, 0, 0)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
										<motion.div
											className={"framer-1kkxqea"}
											data-framer-name={"Line"}
											layoutDependency={layoutDependency}
											layoutId={"ZS9_QIOtY"}
											style={{
												backgroundColor: "rgb(0, 0, 0)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
									</motion.div>
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"qFvCR8WIG"}
										openInNewTab={false}
										scopeId={"uIJgq8jjn"}
									>
										<Image
											as={"a"}
											background={{
												alt: "",
												fit: "fill",
												intrinsicHeight: 99.5,
												intrinsicWidth: 512,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 7.5,
												),
												pixelHeight: 199,
												pixelWidth: 1024,
												sizes: "193px",
												src: "https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199",
												srcSet:
													"https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199 512w,https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?width=1024&height=199 1024w",
											}}
											className={"framer-uraw7y framer-1jzdqhk"}
											data-framer-name={"2793B081-A0A8-408F-A220-D47AF8E92398"}
											layoutDependency={layoutDependency}
											layoutId={"qFvCR8WIG"}
											{...addPropertyOverrides(
												{
													FrgF7jG8i: {
														background: {
															alt: "",
															fit: "fill",
															intrinsicHeight: 99.5,
															intrinsicWidth: 512,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	12 +
																	0 +
																	0 +
																	0 +
																	7.5,
															),
															pixelHeight: 199,
															pixelWidth: 1024,
															sizes: "193px",
															src: "https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199",
															srcSet:
																"https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199 512w,https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?width=1024&height=199 1024w",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</Link>
								</motion.div>
								{isDisplayed1() && (
									<motion.nav
										className={"framer-1qlmjhx"}
										data-framer-name={"Navigation"}
										layoutDependency={layoutDependency}
										layoutId={"AbQ1Nu2NS"}
										style={{
											backgroundColor: "rgba(255, 255, 255, 0)",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
											boxShadow:
												"inset 0.5px 0.5px 0px 0px rgba(134, 134, 134, 0.5)",
										}}
									>
										{isDisplayed1() && (
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "augiA20Il",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "augiA20Il",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks) => (
													<ComponentViewportProvider
														{...addPropertyOverrides(
															{
																FrgF7jG8i: {
																	height: 22,
																	y:
																		(componentViewport?.y || 0) +
																		12 +
																		0 +
																		0 +
																		73 +
																		16 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-fqmoz-container"}
															layoutDependency={layoutDependency}
															layoutId={"LcBl6xnXr-container"}
															nodeId={"LcBl6xnXr"}
															rendersWithMotion={true}
															scopeId={"uIJgq8jjn"}
														>
															{_jsx(stdin_default, {
																caFOTRFF7: "Dental Services",
																height: "100%",
																id: "LcBl6xnXr",
																K4alt95xc: resolvedLinks[0],
																layoutId: "LcBl6xnXr",
																variant: "Cdx8P4Oa0",
																width: "100%",
																...addPropertyOverrides(
																	{
																		FrgF7jG8i: {
																			K4alt95xc: resolvedLinks[1],
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
										{isDisplayed1() && (
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "ESyaFVvmG",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "ESyaFVvmG",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks1) => (
													<ComponentViewportProvider
														{...addPropertyOverrides(
															{
																FrgF7jG8i: {
																	height: 22,
																	y:
																		(componentViewport?.y || 0) +
																		12 +
																		0 +
																		0 +
																		73 +
																		16 +
																		38,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-1pxxse1-container"}
															layoutDependency={layoutDependency}
															layoutId={"LRs9FtMUN-container"}
															nodeId={"LRs9FtMUN"}
															rendersWithMotion={true}
															scopeId={"uIJgq8jjn"}
														>
															{_jsx(stdin_default, {
																caFOTRFF7: "Before & After",
																height: "100%",
																id: "LRs9FtMUN",
																K4alt95xc: resolvedLinks1[0],
																layoutId: "LRs9FtMUN",
																variant: "Cdx8P4Oa0",
																width: "100%",
																...addPropertyOverrides(
																	{
																		FrgF7jG8i: {
																			K4alt95xc: resolvedLinks1[1],
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
										{isDisplayed1() && (
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "a44b8rKAx",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "a44b8rKAx",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks2) => (
													<ComponentViewportProvider
														{...addPropertyOverrides(
															{
																FrgF7jG8i: {
																	height: 22,
																	y:
																		(componentViewport?.y || 0) +
																		12 +
																		0 +
																		0 +
																		73 +
																		16 +
																		76,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-10ie6lz-container"}
															layoutDependency={layoutDependency}
															layoutId={"CHxL3Ij0x-container"}
															nodeId={"CHxL3Ij0x"}
															rendersWithMotion={true}
															scopeId={"uIJgq8jjn"}
														>
															{_jsx(stdin_default, {
																caFOTRFF7: "Our Doctors",
																height: "100%",
																id: "CHxL3Ij0x",
																K4alt95xc: resolvedLinks2[0],
																layoutId: "CHxL3Ij0x",
																variant: "Cdx8P4Oa0",
																width: "100%",
																...addPropertyOverrides(
																	{
																		FrgF7jG8i: {
																			K4alt95xc: resolvedLinks2[1],
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
										{isDisplayed1() && (
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "LvEMpzzqC",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "LvEMpzzqC",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks3) => (
													<ComponentViewportProvider
														{...addPropertyOverrides(
															{
																FrgF7jG8i: {
																	height: 22,
																	y:
																		(componentViewport?.y || 0) +
																		12 +
																		0 +
																		0 +
																		73 +
																		16 +
																		114,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-17c9wuk-container"}
															layoutDependency={layoutDependency}
															layoutId={"FCiRIsi8Y-container"}
															nodeId={"FCiRIsi8Y"}
															rendersWithMotion={true}
															scopeId={"uIJgq8jjn"}
														>
															{_jsx(stdin_default, {
																caFOTRFF7: "Blog",
																height: "100%",
																id: "FCiRIsi8Y",
																K4alt95xc: resolvedLinks3[0],
																layoutId: "FCiRIsi8Y",
																variant: "Cdx8P4Oa0",
																width: "100%",
																...addPropertyOverrides(
																	{
																		FrgF7jG8i: {
																			K4alt95xc: resolvedLinks3[1],
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
										{isDisplayed1() && (
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "DbaMMSXR5",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "DbaMMSXR5",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks4) => (
													<ComponentViewportProvider
														{...addPropertyOverrides(
															{
																FrgF7jG8i: {
																	height: 22,
																	y:
																		(componentViewport?.y || 0) +
																		12 +
																		0 +
																		0 +
																		73 +
																		16 +
																		152,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-jms0ei-container"}
															layoutDependency={layoutDependency}
															layoutId={"j5HtnZw_S-container"}
															nodeId={"j5HtnZw_S"}
															rendersWithMotion={true}
															scopeId={"uIJgq8jjn"}
														>
															{_jsx(stdin_default, {
																caFOTRFF7: "Contact",
																height: "100%",
																id: "j5HtnZw_S",
																K4alt95xc: resolvedLinks4[0],
																layoutId: "j5HtnZw_S",
																variant: "Cdx8P4Oa0",
																width: "100%",
																...addPropertyOverrides(
																	{
																		FrgF7jG8i: {
																			K4alt95xc: resolvedLinks4[1],
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
									</motion.nav>
								)}
								{isDisplayed1() && (
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "DbaMMSXR5",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "DbaMMSXR5",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks5) => (
											<ComponentViewportProvider
												{...addPropertyOverrides(
													{
														FrgF7jG8i: {
															height: 52,
															width: "429px",
															y: (componentViewport?.y || 0) + 12 + 0 + 0 + 299,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-13f9d21-container"}
													layoutDependency={layoutDependency}
													layoutId={"bDMGemqVg-container"}
													nodeId={"bDMGemqVg"}
													rendersWithMotion={true}
													scopeId={"uIJgq8jjn"}
												>
													{_jsx(stdin_default2, {
														AFYf7sdfO: resolvedLinks5[0],
														height: "100%",
														id: "bDMGemqVg",
														layoutId: "bDMGemqVg",
														style: {
															width: "100%",
														},
														variant: "ohHiDnfTr",
														veoDi54e4: "Request an appointment",
														width: "100%",
														...addPropertyOverrides(
															{
																FrgF7jG8i: {
																	AFYf7sdfO: resolvedLinks5[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								)}
							</motion.div>
						</motion.header>
					</Transition>
				)}
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6WJdQ.framer-1jzdqhk, .framer-6WJdQ .framer-1jzdqhk { display: block; }",
	".framer-6WJdQ.framer-ewcmmp { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 50px; justify-content: flex-start; max-width: 1920px; overflow: hidden; padding: 0px; position: relative; width: 429px; }",
	".framer-6WJdQ .framer-1kjitb1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: 53px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 429px; z-index: 1; }",
	".framer-6WJdQ .framer-uj39id { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: 53px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 429px; }",
	".framer-6WJdQ .framer-12w9xve { align-content: center; align-items: center; aspect-ratio: 1 / 1; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: var(--framer-aspect-ratio-supported, 24px); justify-content: center; overflow: hidden; padding: 0px; position: absolute; right: 36px; top: 47%; width: 24px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-6WJdQ .framer-gs4s1u, .framer-6WJdQ .framer-1kkxqea { flex: none; height: 2px; overflow: hidden; position: relative; width: 18px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-6WJdQ .framer-uraw7y { aspect-ratio: 5.1457286432160805 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 38px); overflow: visible; position: relative; text-decoration: none; width: 193px; }",
	".framer-6WJdQ .framer-1qlmjhx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; min-height: 206px; overflow: visible; padding: 16px 32px 16px 32px; position: relative; width: 100%; z-index: 1; }",
	".framer-6WJdQ .framer-fqmoz-container, .framer-6WJdQ .framer-1pxxse1-container, .framer-6WJdQ .framer-10ie6lz-container, .framer-6WJdQ .framer-17c9wuk-container, .framer-6WJdQ .framer-jms0ei-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-6WJdQ .framer-13f9d21-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }",
	".framer-6WJdQ.framer-v-adczhb.framer-ewcmmp { height: 426px; padding: 12px; width: 390px; }",
	".framer-6WJdQ.framer-v-adczhb .framer-1qlmjhx { min-height: unset; }",
	".framer-6WJdQ.framer-v-y3y3n3.framer-ewcmmp { height: min-content; }",
	'.framer-6WJdQ[data-border="true"]::after, .framer-6WJdQ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameruIJgq8jjn = withCSS(Component, css, "framer-6WJdQ");
var stdin_default3 = FrameruIJgq8jjn;
FrameruIJgq8jjn.displayName = "Header Section 3";
FrameruIJgq8jjn.defaultProps = {
	height: 50,
	width: 429,
};
addPropertyControls(FrameruIJgq8jjn, {
	variant: {
		options: ["o4vq3rsib", "OrvQ15ubb", "FrgF7jG8i", "LLaZ1Y4wA"],
		optionTitles: ["Desktop", "Mobile Closed", "Mobile Open", "Variant 4"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameruIJgq8jjn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...MenuItemFonts,
		...PrimaryButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header-section-3
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderSection3FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var header_section_3_default = ComponentWithRoot;
export { header_section_3_default as default };
