// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-C65GIQBU.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-ZOKOWKTV.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:header-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/VvmqbhhXdauILqgt3Nge/06wmDbdllRHgLxmSbWTM/xQKegUSOO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MenuItemFonts = getFonts(stdin_default);
var PrimaryButtonFonts = getFonts(stdin_default2);
var serializationHash = "framer-bavwp";
var variantClassNames = {
	TJ79yX9NN: "framer-v-1buvo6m",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "TJ79yX9NN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap16yfney = activeVariantCallback(async (...args) => {
		setVariant("sT1SwAXAc");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.header
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1buvo6m",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"TJ79yX9NN"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.header
							className={"framer-ju638d"}
							data-framer-name={"Mobile Closed"}
							layoutDependency={layoutDependency}
							layoutId={"YbkXjNq4S"}
						>
							<motion.div
								className={"framer-ybbng7"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"OmcJK5gkx"}
							>
								<motion.div
									className={"framer-fm0vjr"}
									data-framer-name={"Logo"}
									layoutDependency={layoutDependency}
									layoutId={"bUEx2NR8r"}
								>
									<motion.div
										className={"framer-qhwf4g"}
										data-framer-name={"Mobile Menu Icon"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"mocNKV9al"}
										onTap={onTap16yfney}
										style={{
											backgroundColor: "rgba(255, 255, 255, 0)",
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
										}}
									>
										<motion.div
											className={"framer-pnrzie"}
											data-framer-name={"Line"}
											layoutDependency={layoutDependency}
											layoutId={"oiVu5776V"}
											style={{
												backgroundColor: "rgb(0, 0, 0)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
										<motion.div
											className={"framer-1608hef"}
											data-framer-name={"Line"}
											layoutDependency={layoutDependency}
											layoutId={"FPCi_RvQr"}
											style={{
												backgroundColor: "rgb(0, 0, 0)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
									</motion.div>
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"DZOThP_hC"}
										openInNewTab={false}
										scopeId={"xQKegUSOO"}
									>
										<Image
											as={"a"}
											background={{
												alt: "",
												fit: "fill",
												intrinsicHeight: 99.5,
												intrinsicWidth: 512,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														12 +
														0 +
														12 +
														0 +
														0 +
														0 +
														0,
												),
												pixelHeight: 199,
												pixelWidth: 1024,
												sizes: "193px",
												src: "https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199",
												srcSet:
													"https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?scale-down-to=512&width=1024&height=199 512w,https://framerusercontent.com/images/K41fEMltahDzJCinCfAWG2ZSw.jpg?width=1024&height=199 1024w",
											}}
											className={"framer-db2rpp framer-fdc78p"}
											data-framer-name={"2793B081-A0A8-408F-A220-D47AF8E92398"}
											layoutDependency={layoutDependency}
											layoutId={"DZOThP_hC"}
										/>
									</Link>
								</motion.div>
								<motion.nav
									className={"framer-1sr6vn7"}
									data-framer-name={"Navigation"}
									layoutDependency={layoutDependency}
									layoutId={"K1zwkV_xY"}
									style={{
										backgroundColor: "rgba(255, 255, 255, 0)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
										boxShadow:
											"inset 0.5px 0.5px 0px 0px rgba(134, 134, 134, 0.5)",
									}}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={22}
												y={
													(componentViewport?.y || 0) +
													12 +
													0 +
													12 +
													0 +
													0 +
													68 +
													16 +
													0
												}
											>
												<SmartComponentScopedContainer
													className={"framer-1ypzg1q-container"}
													layoutDependency={layoutDependency}
													layoutId={"gC0Ue7Dnr-container"}
													nodeId={"gC0Ue7Dnr"}
													rendersWithMotion={true}
													scopeId={"xQKegUSOO"}
												>
													{_jsx(stdin_default, {
														caFOTRFF7: "Dental Services",
														height: "100%",
														id: "gC0Ue7Dnr",
														K4alt95xc: resolvedLinks[0],
														layoutId: "gC0Ue7Dnr",
														variant: "Cdx8P4Oa0",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "ESyaFVvmG",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={22}
												y={
													(componentViewport?.y || 0) +
													12 +
													0 +
													12 +
													0 +
													0 +
													68 +
													16 +
													38
												}
											>
												<SmartComponentScopedContainer
													className={"framer-6v7z55-container"}
													layoutDependency={layoutDependency}
													layoutId={"WPTVAq_gy-container"}
													nodeId={"WPTVAq_gy"}
													rendersWithMotion={true}
													scopeId={"xQKegUSOO"}
												>
													{_jsx(stdin_default, {
														caFOTRFF7: "Before & After",
														height: "100%",
														id: "WPTVAq_gy",
														K4alt95xc: resolvedLinks1[0],
														layoutId: "WPTVAq_gy",
														variant: "Cdx8P4Oa0",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "a44b8rKAx",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks2) => (
											<ComponentViewportProvider
												height={22}
												y={
													(componentViewport?.y || 0) +
													12 +
													0 +
													12 +
													0 +
													0 +
													68 +
													16 +
													76
												}
											>
												<SmartComponentScopedContainer
													className={"framer-19uhyx6-container"}
													layoutDependency={layoutDependency}
													layoutId={"zK5dt36kz-container"}
													nodeId={"zK5dt36kz"}
													rendersWithMotion={true}
													scopeId={"xQKegUSOO"}
												>
													{_jsx(stdin_default, {
														caFOTRFF7: "Our Doctors",
														height: "100%",
														id: "zK5dt36kz",
														K4alt95xc: resolvedLinks2[0],
														layoutId: "zK5dt36kz",
														variant: "Cdx8P4Oa0",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "LvEMpzzqC",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks3) => (
											<ComponentViewportProvider
												height={22}
												y={
													(componentViewport?.y || 0) +
													12 +
													0 +
													12 +
													0 +
													0 +
													68 +
													16 +
													114
												}
											>
												<SmartComponentScopedContainer
													className={"framer-187biiy-container"}
													layoutDependency={layoutDependency}
													layoutId={"zjHU3K2Hm-container"}
													nodeId={"zjHU3K2Hm"}
													rendersWithMotion={true}
													scopeId={"xQKegUSOO"}
												>
													{_jsx(stdin_default, {
														caFOTRFF7: "Blog",
														height: "100%",
														id: "zjHU3K2Hm",
														K4alt95xc: resolvedLinks3[0],
														layoutId: "zjHU3K2Hm",
														variant: "Cdx8P4Oa0",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "DbaMMSXR5",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks4) => (
											<ComponentViewportProvider
												height={22}
												y={
													(componentViewport?.y || 0) +
													12 +
													0 +
													12 +
													0 +
													0 +
													68 +
													16 +
													152
												}
											>
												<SmartComponentScopedContainer
													className={"framer-1snsc57-container"}
													layoutDependency={layoutDependency}
													layoutId={"HdjY3tLp1-container"}
													nodeId={"HdjY3tLp1"}
													rendersWithMotion={true}
													scopeId={"xQKegUSOO"}
												>
													{_jsx(stdin_default, {
														caFOTRFF7: "Contact",
														height: "100%",
														id: "HdjY3tLp1",
														K4alt95xc: resolvedLinks4[0],
														layoutId: "HdjY3tLp1",
														variant: "Cdx8P4Oa0",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.nav>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "DbaMMSXR5",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks5) => (
										<ComponentViewportProvider
											height={52}
											width={"529px"}
											y={
												(componentViewport?.y || 0) + 12 + 0 + 12 + 0 + 0 + 304
											}
										>
											<SmartComponentScopedContainer
												className={"framer-2yvs4x-container"}
												layoutDependency={layoutDependency}
												layoutId={"S4AxJERaf-container"}
												nodeId={"S4AxJERaf"}
												rendersWithMotion={true}
												scopeId={"xQKegUSOO"}
											>
												{_jsx(stdin_default2, {
													AFYf7sdfO: resolvedLinks5[0],
													height: "100%",
													id: "S4AxJERaf",
													layoutId: "S4AxJERaf",
													style: {
														width: "100%",
													},
													variant: "ohHiDnfTr",
													veoDi54e4: "Request an appointment",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							</motion.div>
						</motion.header>
					</motion.header>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bavwp.framer-fdc78p, .framer-bavwp .framer-fdc78p { display: block; }",
	".framer-bavwp.framer-1buvo6m { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 60px; justify-content: flex-start; overflow: hidden; padding: 12px; position: relative; width: 768px; }",
	".framer-bavwp .framer-ju638d { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 60px; justify-content: flex-start; overflow: hidden; padding: 12px; position: relative; width: 557px; }",
	".framer-bavwp .framer-ybbng7 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 529px; z-index: 1; }",
	".framer-bavwp .framer-fm0vjr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 526px; }",
	".framer-bavwp .framer-qhwf4g { align-content: center; align-items: center; aspect-ratio: 1 / 1; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: var(--framer-aspect-ratio-supported, 24px); justify-content: center; overflow: hidden; padding: 0px; position: absolute; right: 36px; top: -2px; width: 24px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-bavwp .framer-pnrzie, .framer-bavwp .framer-1608hef { flex: none; height: 2px; overflow: hidden; position: relative; width: 18px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-bavwp .framer-db2rpp { aspect-ratio: 5.1457286432160805 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 38px); overflow: visible; position: relative; text-decoration: none; width: 193px; }",
	".framer-bavwp .framer-1sr6vn7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 32px 16px 32px; position: relative; width: 100%; z-index: 1; }",
	".framer-bavwp .framer-1ypzg1q-container, .framer-bavwp .framer-6v7z55-container, .framer-bavwp .framer-19uhyx6-container, .framer-bavwp .framer-187biiy-container, .framer-bavwp .framer-1snsc57-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-bavwp .framer-2yvs4x-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }",
];
var FramerxQKegUSOO = withCSS(Component, css, "framer-bavwp");
var stdin_default3 = FramerxQKegUSOO;
FramerxQKegUSOO.displayName = "Header Mobile";
FramerxQKegUSOO.defaultProps = {
	height: 60,
	width: 768,
};
addFonts(
	FramerxQKegUSOO,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...MenuItemFonts,
		...PrimaryButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var header_mobile_default = ComponentWithRoot;
export { header_mobile_default as default };
