// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-2XXMBWNK.js";
import { Ticker } from "./chunks/chunk-I5OAE6PV.js";
import "./chunks/chunk-35FZW2DU.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-KTNTSTR4.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-QQCB4RLB.js";
import { stdin_default as stdin_default5 } from "./chunks/chunk-ZCU3CHYE.js";
import { stdin_default } from "./chunks/chunk-EMEZPYR5.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:hero-with-carousel-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/LBcm1o8VLxyYtsEOf7Qv/IBhuoQstL0YL4XShXugl/Uho4dG5OK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageCard1Fonts = getFonts(stdin_default);
var ImageCard2MobileFonts = getFonts(stdin_default3);
var ImageCard3MobileFonts = getFonts(stdin_default2);
var ImageCard4MobileFonts = getFonts(stdin_default5);
var TickerFonts = getFonts(Ticker);
var HeroMobileFonts = getFonts(stdin_default4);
var serializationHash = "framer-oGlQm";
var variantClassNames = {
	utLgnuGLY: "framer-v-1p10mux",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "utLgnuGLY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1p10mux",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"utLgnuGLY"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(69, 205, 255, 0)",
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-uuioca-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"D_jJEOR8y-container"}
								nodeId={"D_jJEOR8y"}
								rendersWithMotion={true}
								scopeId={"Uho4dG5OK"}
							>
								<Ticker
									alignment={"center"}
									direction={"left"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={10}
									height={"100%"}
									hoverFactor={1}
									id={"D_jJEOR8y"}
									layoutId={"D_jJEOR8y"}
									padding={10}
									paddingBottom={10}
									paddingLeft={10}
									paddingPerSide={false}
									paddingRight={10}
									paddingTop={10}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-12fhgbw-container"}
												data-framer-name={"Image Card 1 Mobile"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"GBPfOyFax-container"}
												name={"Image Card 1 Mobile"}
												nodeId={"GBPfOyFax"}
												rendersWithMotion={true}
												scopeId={"Uho4dG5OK"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													id: "GBPfOyFax",
													layoutId: "GBPfOyFax",
													name: "Image Card 1 Mobile",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-13n5a3c-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"MdInJttdG-container"}
												nodeId={"MdInJttdG"}
												rendersWithMotion={true}
												scopeId={"Uho4dG5OK"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "MdInJttdG",
													layoutId: "MdInJttdG",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-11kp6uc-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"cQKDhyhcH-container"}
												nodeId={"cQKDhyhcH"}
												rendersWithMotion={true}
												scopeId={"Uho4dG5OK"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "cQKDhyhcH",
													layoutId: "cQKDhyhcH",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-an77sl-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"bw9XZiTT7-container"}
												nodeId={"bw9XZiTT7"}
												rendersWithMotion={true}
												scopeId={"Uho4dG5OK"}
											>
												{_jsx(stdin_default5, {
													height: "100%",
													id: "bw9XZiTT7",
													layoutId: "bw9XZiTT7",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									speed={10}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={478}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 5}
						>
							<SmartComponentScopedContainer
								className={"framer-f3w81q-container"}
								layoutDependency={layoutDependency}
								layoutId={"Rjt1mWuf9-container"}
								nodeId={"Rjt1mWuf9"}
								rendersWithMotion={true}
								scopeId={"Uho4dG5OK"}
							>
								{_jsx(stdin_default4, {
									height: "100%",
									id: "Rjt1mWuf9",
									layoutId: "Rjt1mWuf9",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oGlQm.framer-azj3z4, .framer-oGlQm .framer-azj3z4 { display: block; }",
	".framer-oGlQm.framer-1p10mux { height: 848px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 390px; }",
	".framer-oGlQm .framer-uuioca-container { bottom: 14px; flex: none; height: 337px; left: -5px; position: absolute; right: -5px; }",
	".framer-oGlQm .framer-12fhgbw-container, .framer-oGlQm .framer-13n5a3c-container, .framer-oGlQm .framer-11kp6uc-container, .framer-oGlQm .framer-an77sl-container { height: 319px; position: relative; width: 267px; }",
	".framer-oGlQm .framer-f3w81q-container { flex: none; height: 478px; left: 0px; position: absolute; right: 0px; top: 5px; }",
];
var FramerUho4dG5OK = withCSS(Component, css, "framer-oGlQm");
var stdin_default6 = FramerUho4dG5OK;
FramerUho4dG5OK.displayName = "Hero With Carousel Mobile";
FramerUho4dG5OK.defaultProps = {
	height: 848,
	width: 390,
};
addFonts(
	FramerUho4dG5OK,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ImageCard1Fonts,
		...ImageCard2MobileFonts,
		...ImageCard3MobileFonts,
		...ImageCard4MobileFonts,
		...TickerFonts,
		...HeroMobileFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-with-carousel-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroWithCarouselMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var hero_with_carousel_mobile_default = ComponentWithRoot;
export { hero_with_carousel_mobile_default as default };
