// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default5 } from "./chunks/chunk-R5SFGPFR.js";
import { Ticker } from "./chunks/chunk-I5OAE6PV.js";
import "./chunks/chunk-35FZW2DU.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-KTNTSTR4.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-QQCB4RLB.js";
import { stdin_default as stdin_default4 } from "./chunks/chunk-ZCU3CHYE.js";
import { stdin_default } from "./chunks/chunk-EMEZPYR5.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:hero-with-carousels-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/N0i9KVBT1Ugdyc5lAwKp/Xu3cGy58zGYjPbZasPlR/WDpRSm9aJ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageCard1Fonts = getFonts(stdin_default);
var ImageCard2MobileFonts = getFonts(stdin_default3);
var ImageCard3MobileFonts = getFonts(stdin_default2);
var ImageCard4MobileFonts = getFonts(stdin_default4);
var TickerFonts = getFonts(Ticker);
var HeroDesktopFonts = getFonts(stdin_default5);
var cycleOrder = ["QfImVVAH4", "aeoFy0Ii5"];
var serializationHash = "framer-o9t2r";
var variantClassNames = {
	aeoFy0Ii5: "framer-v-34argr",
	QfImVVAH4: "framer-v-15duk2a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "QfImVVAH4",
	Phone: "aeoFy0Ii5",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "QfImVVAH4",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "QfImVVAH4",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "aeoFy0Ii5") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-15duk2a",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"QfImVVAH4"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(153, 238, 255, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								aeoFy0Ii5: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1c5p1s3-container"}
								data-framer-name={"Carousel 2 Desktop"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"foDTuaW9q-container"}
								name={"Carousel 2 Desktop"}
								nodeId={"foDTuaW9q"}
								rendersWithMotion={true}
								scopeId={"WDpRSm9aJ"}
							>
								<Ticker
									alignment={"center"}
									direction={"top"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={10}
									height={"100%"}
									hoverFactor={1}
									id={"foDTuaW9q"}
									layoutId={"foDTuaW9q"}
									name={"Carousel 2 Desktop"}
									padding={10}
									paddingBottom={10}
									paddingLeft={10}
									paddingPerSide={false}
									paddingRight={10}
									paddingTop={10}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-1x5tr25-container"}
												data-framer-name={"Image Card 1 Mobile"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"WlOhwaEpm-container"}
												name={"Image Card 1 Mobile"}
												nodeId={"WlOhwaEpm"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													id: "WlOhwaEpm",
													layoutId: "WlOhwaEpm",
													name: "Image Card 1 Mobile",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-1h5t8lx-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"SmayEgRXP-container"}
												nodeId={"SmayEgRXP"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "SmayEgRXP",
													layoutId: "SmayEgRXP",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-ki1ewi-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"KDoEJlH4Y-container"}
												nodeId={"KDoEJlH4Y"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "KDoEJlH4Y",
													layoutId: "KDoEJlH4Y",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-1bc3sc9-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"Ck0Vq877G-container"}
												nodeId={"Ck0Vq877G"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default4, {
													height: "100%",
													id: "Ck0Vq877G",
													layoutId: "Ck0Vq877G",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									speed={60}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-l9bya-container"}
								data-framer-name={"Carousel 1 Desktop"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"ZTRSdOge2-container"}
								name={"Carousel 1 Desktop"}
								nodeId={"ZTRSdOge2"}
								rendersWithMotion={true}
								scopeId={"WDpRSm9aJ"}
							>
								<Ticker
									alignment={"center"}
									direction={"bottom"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={10}
									height={"100%"}
									hoverFactor={1}
									id={"ZTRSdOge2"}
									layoutId={"ZTRSdOge2"}
									name={"Carousel 1 Desktop"}
									padding={10}
									paddingBottom={10}
									paddingLeft={10}
									paddingPerSide={false}
									paddingRight={10}
									paddingTop={10}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-1x5tr25-container"}
												data-framer-name={"Image Card 1 Mobile"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"WlOhwaEpm-container"}
												name={"Image Card 1 Mobile"}
												nodeId={"WlOhwaEpm"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													id: "WlOhwaEpm",
													layoutId: "WlOhwaEpm",
													name: "Image Card 1 Mobile",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-1h5t8lx-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"SmayEgRXP-container"}
												nodeId={"SmayEgRXP"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "SmayEgRXP",
													layoutId: "SmayEgRXP",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-ki1ewi-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"KDoEJlH4Y-container"}
												nodeId={"KDoEJlH4Y"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "KDoEJlH4Y",
													layoutId: "KDoEJlH4Y",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={319} width={"267px"}>
											<SmartComponentScopedContainer
												className={"framer-1bc3sc9-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"Ck0Vq877G-container"}
												nodeId={"Ck0Vq877G"}
												rendersWithMotion={true}
												scopeId={"WDpRSm9aJ"}
											>
												{_jsx(stdin_default4, {
													height: "100%",
													id: "Ck0Vq877G",
													layoutId: "Ck0Vq877G",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									speed={60}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						{isDisplayed() && (
							<ComponentViewportProvider
								height={874}
								width={"707px"}
								y={(componentViewport?.y || 0) + -10}
							>
								<SmartComponentScopedContainer
									className={"framer-19p54jy-container"}
									layoutDependency={layoutDependency}
									layoutId={"UU416pVy3-container"}
									nodeId={"UU416pVy3"}
									rendersWithMotion={true}
									scopeId={"WDpRSm9aJ"}
								>
									{_jsx(stdin_default5, {
										height: "100%",
										id: "UU416pVy3",
										layoutId: "UU416pVy3",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-o9t2r.framer-1obvsju, .framer-o9t2r .framer-1obvsju { display: block; }",
	".framer-o9t2r.framer-15duk2a { height: 1050px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-o9t2r .framer-1c5p1s3-container { flex: none; height: 864px; left: 862px; position: absolute; top: 0px; width: 314px; }",
	".framer-o9t2r .framer-1x5tr25-container, .framer-o9t2r .framer-1h5t8lx-container, .framer-o9t2r .framer-ki1ewi-container, .framer-o9t2r .framer-1bc3sc9-container { height: 319px; position: relative; width: 267px; }",
	".framer-o9t2r .framer-l9bya-container { flex: none; height: 876px; left: 1170px; position: absolute; top: 1px; width: 314px; }",
	".framer-o9t2r .framer-19p54jy-container { flex: none; height: 874px; left: 0px; position: absolute; top: -10px; width: 707px; }",
	".framer-o9t2r.framer-v-34argr.framer-15duk2a { width: 390px; }",
	".framer-o9t2r.framer-v-34argr .framer-1c5p1s3-container { left: unset; right: -786px; }",
	".framer-o9t2r.framer-v-34argr .framer-l9bya-container { left: unset; right: -1094px; }",
];
var FramerWDpRSm9aJ = withCSS(Component, css, "framer-o9t2r");
var stdin_default6 = FramerWDpRSm9aJ;
FramerWDpRSm9aJ.displayName = "HeroWithCarouselsDesktop";
FramerWDpRSm9aJ.defaultProps = {
	height: 1050,
	width: 1700,
};
addPropertyControls(FramerWDpRSm9aJ, {
	variant: {
		options: ["QfImVVAH4", "aeoFy0Ii5"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerWDpRSm9aJ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ImageCard1Fonts,
		...ImageCard2MobileFonts,
		...ImageCard3MobileFonts,
		...ImageCard4MobileFonts,
		...TickerFonts,
		...HeroDesktopFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-with-carousels-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aeoFy0Ii5",
	"2xl": "QfImVVAH4",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroWithCarouselsDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var hero_with_carousels_desktop_default = ComponentWithRoot;
export { hero_with_carousels_desktop_default as default };
