// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-N5D5Y7KW.js";
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
} from "./chunks/chunk-XBS63SYV.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:latest-from-the-blog
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/m7aRPRTHf7pUo1MMJDEK/nvvVnfvKQXul9fuedns2/gpk0GIUxx.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-4MpNL";
var variantClassNames = {
	Yf85Ix1Wc: "framer-v-6fy6qe",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Yf85Ix1Wc",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-6fy6qe",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Yf85Ix1Wc"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-12t7y1b"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"SoeGooWru"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h6
									className={"framer-styles-preset-15xgadr"}
									data-styles-preset={"KNPSuSphB"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									{"Latest from the Blog"}
								</motion.h6>
							</React.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 3120,
								intrinsicWidth: 2080,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 712) -
										394,
								),
								pixelHeight: 6240,
								pixelWidth: 4160,
								sizes: "371px",
								src: "https://framerusercontent.com/images/qer3G9fo0lqTXSqUix0UOps0DF4.jpg?scale-down-to=4096&width=4160&height=6240",
								srcSet:
									"https://framerusercontent.com/images/qer3G9fo0lqTXSqUix0UOps0DF4.jpg?scale-down-to=1024&width=4160&height=6240 682w,https://framerusercontent.com/images/qer3G9fo0lqTXSqUix0UOps0DF4.jpg?scale-down-to=2048&width=4160&height=6240 1365w,https://framerusercontent.com/images/qer3G9fo0lqTXSqUix0UOps0DF4.jpg?scale-down-to=4096&width=4160&height=6240 2730w,https://framerusercontent.com/images/qer3G9fo0lqTXSqUix0UOps0DF4.jpg?width=4160&height=6240 4160w",
							}}
							className={"framer-r5h36j"}
							data-framer-name={"Pexels-n-voitkevich-10060923"}
							layoutDependency={layoutDependency}
							layoutId={"gcuRvRxm9"}
							style={{
								borderBottomLeftRadius: 6,
								borderBottomRightRadius: 6,
								borderTopLeftRadius: 6,
								borderTopRightRadius: 6,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 2564,
								intrinsicWidth: 1709.5,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 712) -
										394,
								),
								pixelHeight: 5128,
								pixelWidth: 3419,
								sizes: "371px",
								src: "https://framerusercontent.com/images/T72qnqpHzVBpmGtv0gE4vWYsTw.jpg?scale-down-to=4096&width=3419&height=5128",
								srcSet:
									"https://framerusercontent.com/images/T72qnqpHzVBpmGtv0gE4vWYsTw.jpg?scale-down-to=1024&width=3419&height=5128 682w,https://framerusercontent.com/images/T72qnqpHzVBpmGtv0gE4vWYsTw.jpg?scale-down-to=2048&width=3419&height=5128 1365w,https://framerusercontent.com/images/T72qnqpHzVBpmGtv0gE4vWYsTw.jpg?scale-down-to=4096&width=3419&height=5128 2730w,https://framerusercontent.com/images/T72qnqpHzVBpmGtv0gE4vWYsTw.jpg?width=3419&height=5128 3419w",
							}}
							className={"framer-1j6te55"}
							data-framer-name={"Pexels-cottonbro-6502307"}
							layoutDependency={layoutDependency}
							layoutId={"K7u4m0Mnz"}
							style={{
								borderBottomLeftRadius: 6,
								borderBottomRightRadius: 6,
								borderTopLeftRadius: 6,
								borderTopRightRadius: 6,
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ldh26t"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ivGeAlGag"}
							style={{
								"--extracted-1w1cjl5": "rgb(8, 8, 8)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h6
									className={"framer-styles-preset-cxe34z"}
									data-styles-preset={"p3RywmB7g"}
									style={{
										"--framer-text-color":
											"var(--extracted-1w1cjl5, rgb(8, 8, 8))",
									}}
								>
									{"3 Tips to Help You Get Restorative Sleep"}
								</motion.h6>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-hzg6bk"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"DV1ODXQLh"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h6
									className={"framer-styles-preset-cxe34z"}
									data-styles-preset={"p3RywmB7g"}
								>
									<Link
										href={
											"https://bensonhurstdentalcare.com/blog/top-3-toothbrushes-for-receding-gums"
										}
										motionChild={true}
										nodeId={"DV1ODXQLh"}
										openInNewTab={false}
										relValues={[]}
										scopeId={"gpk0GIUxx"}
										smoothScroll={false}
									>
										<motion.a
											className={"framer-styles-preset-1j1qs7m"}
											data-styles-preset={"lk48S9NjM"}
										>
											{"Top 3 Toothbrushes for Receding Gums"}
										</motion.a>
									</Link>
								</motion.h6>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-rslhv9"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"JieKhcTXw"}
							style={{
								"--extracted-1w1cjl5": "rgb(0, 0, 0)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h6
									className={"framer-styles-preset-cxe34z"}
									data-styles-preset={"p3RywmB7g"}
									style={{
										"--framer-text-color":
											"var(--extracted-1w1cjl5, rgb(0, 0, 0))",
									}}
								>
									{
										"7 Things About Dental Amalgam Your Dentist Wants You to Know"
									}
								</motion.h6>
							</React.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 1878.5,
								intrinsicWidth: 2818,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 712) -
										394,
								),
								pixelHeight: 3757,
								pixelWidth: 5636,
								sizes: "370px",
								src: "https://framerusercontent.com/images/K8WBFn86XYuAgtq24ix5p3i0g.jpg?scale-down-to=4096&width=5636&height=3757",
								srcSet:
									"https://framerusercontent.com/images/K8WBFn86XYuAgtq24ix5p3i0g.jpg?scale-down-to=512&width=5636&height=3757 512w,https://framerusercontent.com/images/K8WBFn86XYuAgtq24ix5p3i0g.jpg?scale-down-to=1024&width=5636&height=3757 1024w,https://framerusercontent.com/images/K8WBFn86XYuAgtq24ix5p3i0g.jpg?scale-down-to=2048&width=5636&height=3757 2048w,https://framerusercontent.com/images/K8WBFn86XYuAgtq24ix5p3i0g.jpg?scale-down-to=4096&width=5636&height=3757 4096w,https://framerusercontent.com/images/K8WBFn86XYuAgtq24ix5p3i0g.jpg?width=5636&height=3757 5636w",
							}}
							className={"framer-ihe1p0"}
							data-framer-name={"Pexels-asphotography-216729"}
							layoutDependency={layoutDependency}
							layoutId={"CYTaeYzCu"}
							style={{
								borderBottomLeftRadius: 6,
								borderBottomRightRadius: 6,
								borderTopLeftRadius: 6,
								borderTopRightRadius: 6,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4MpNL.framer-1vebj13, .framer-4MpNL .framer-1vebj13 { display: block; }",
	".framer-4MpNL.framer-6fy6qe { height: 712px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-4MpNL .framer-12t7y1b { flex: none; height: 151px; left: 263px; position: absolute; top: 0px; white-space: pre-wrap; width: 523px; word-break: break-word; word-wrap: break-word; }",
	".framer-4MpNL .framer-r5h36j { bottom: 149px; flex: none; height: 245px; left: 263px; overflow: visible; position: absolute; width: 371px; }",
	".framer-4MpNL .framer-1j6te55 { bottom: 149px; flex: none; height: 245px; left: 1079px; overflow: visible; position: absolute; width: 371px; }",
	".framer-4MpNL .framer-1ldh26t { flex: none; height: 52px; left: 263px; position: absolute; top: 254px; white-space: pre-wrap; width: 321px; word-break: break-word; word-wrap: break-word; }",
	".framer-4MpNL .framer-hzg6bk { flex: none; height: 64px; left: calc(47.23529411764708% - 299px / 2); position: absolute; top: 254px; white-space: pre-wrap; width: 299px; word-break: break-word; word-wrap: break-word; }",
	".framer-4MpNL .framer-rslhv9 { flex: none; height: 78px; left: 1079px; position: absolute; top: 240px; white-space: pre-wrap; width: 359px; word-break: break-word; word-wrap: break-word; }",
	".framer-4MpNL .framer-ihe1p0 { bottom: 149px; flex: none; height: 245px; left: calc(50.00000000000002% - 370px / 2); overflow: visible; position: absolute; width: 370px; }",
	...css3,
	...css2,
	...css,
];
var Framergpk0GIUxx = withCSS(Component, css4, "framer-4MpNL");
var stdin_default = Framergpk0GIUxx;
Framergpk0GIUxx.displayName = "Latest From The Blog";
Framergpk0GIUxx.defaultProps = {
	height: 712,
	width: 1700,
};
addFonts(
	Framergpk0GIUxx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:latest-from-the-blog
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LatestFromTheBlogFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var latest_from_the_blog_default = ComponentWithRoot;
export { latest_from_the_blog_default as default };
