// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:mobile-open
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kbYL6gjYFYjnPsU1KoTA/huQFxkSoDu2Ax2Ok4Db4/z2yvWuiPQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var serializationHash = "framer-z4CX8";
var variantClassNames = {
	xhDgTOTxn: "framer-v-9zjk7m",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "xhDgTOTxn",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<MotionDivWithFXWithOptimizedAppearEffect
						{...restProps}
						{...gestureHandlers}
						__framer__presenceAnimate={animation}
						__framer__presenceInitial={animation1}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-9zjk7m",
							className,
							classNames,
						)}
						data-framer-appear-id={"9zjk7m"}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"xhDgTOTxn"}
						optimized={true}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							boxShadow: "0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
							...style,
						}}
					>
						<motion.div
							className={"framer-vuisq6"}
							layoutDependency={layoutDependency}
							layoutId={"FxrI_FXir"}
							style={{
								backgroundColor: "rgb(237, 200, 96)",
								borderBottomLeftRadius: 30,
								borderBottomRightRadius: 30,
								borderTopLeftRadius: 30,
								borderTopRightRadius: 30,
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-xfrmmc"}
								fonts={["GF;Actor-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"KdSQnn4gB"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate1}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7QWN0b3ItcmVndWxhcg==",
											"--framer-font-family":
												'"Actor", "Actor Placeholder", sans-serif',
											"--framer-font-size": "17px",
										}}
									>
										{"Request an appointment"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 53,
								intrinsicWidth: 101,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 150) * 0.480769230769231 -
											22.5),
								),
								pixelHeight: 106,
								pixelWidth: 202,
								positionX: "left",
								positionY: "center",
								src: "https://framerusercontent.com/images/ySspoccrCt2TtCPaRlVs4HvScxM.png?width=202&height=106",
							}}
							className={"framer-1o86st9"}
							data-framer-name={"Screenshot 2568-10-28 at 19.58.29"}
							layoutDependency={layoutDependency}
							layoutId={"kqYShMEHJ"}
						/>
					</MotionDivWithFXWithOptimizedAppearEffect>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-z4CX8.framer-1kslt5m, .framer-z4CX8 .framer-1kslt5m { display: block; }",
	".framer-z4CX8.framer-9zjk7m { height: 150px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-z4CX8 .framer-vuisq6 { flex: none; height: 45px; left: calc(50.00000000000002% - 225px / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 341px; width: 225px; will-change: var(--framer-will-change-override, transform); }",
	".framer-z4CX8 .framer-xfrmmc { flex: none; height: auto; left: 50%; position: absolute; top: 49%; white-space: pre; width: auto; }",
	".framer-z4CX8 .framer-1o86st9 { flex: none; height: 45px; left: 291px; overflow: visible; position: absolute; top: calc(48.0769230769231% - 45px / 2); width: 46px; }",
];
var Framerz2yvWuiPQ = withCSS(Component, css, "framer-z4CX8");
var stdin_default = Framerz2yvWuiPQ;
Framerz2yvWuiPQ.displayName = "Mobile Open";
Framerz2yvWuiPQ.defaultProps = {
	height: 150,
	width: 200,
};
addFonts(
	Framerz2yvWuiPQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Actor",
					source: "google",
					style: "normal",
					uiFamilyName: "Actor",
					url: "https://fonts.gstatic.com/s/actor/v18/wEOzEBbCkc5cO3ehXygtUMIO.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mobile-open
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MobileOpenFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var mobile_open_default = ComponentWithRoot;
export { mobile_open_default as default };
