// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default5 } from "./chunks/chunk-4WAJQZOZ.js";
import { stdin_default as stdin_default4 } from "./chunks/chunk-H2GCW4GG.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-XFMHXJRT.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-45OQUSG3.js";
import { Carousel } from "./chunks/chunk-ENEUJRQD.js";
import "./chunks/chunk-JYPPSARU.js";
import { stdin_default } from "./chunks/chunk-CIYRDFZT.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:reviews-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vQz2z40dclwbKBOE2bQ2/67I16po2Fc8vKXXxzAP7/trO8tNLRU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ReviewsBackgroundAndTextMobileFonts = getFonts(stdin_default2);
var Review1MobileFonts = getFonts(stdin_default5);
var Review2MobileFonts = getFonts(stdin_default4);
var Review3MobileFonts = getFonts(stdin_default3);
var Review4MobileFonts = getFonts(stdin_default);
var CarouselFonts = getFonts(Carousel);
var serializationHash = "framer-C0sAA";
var variantClassNames = {
	Sa1GSo0lR: "framer-v-s2165h",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Sa1GSo0lR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-s2165h",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Sa1GSo0lR"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(51, 170, 255, 0)",
							...style,
						}}
					>
						<ComponentViewportProvider
							height={(componentViewport?.height || 444) - 0}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-g4cswo-container"}
								layoutDependency={layoutDependency}
								layoutId={"baKkDJqjT-container"}
								nodeId={"baKkDJqjT"}
								rendersWithMotion={true}
								scopeId={"trO8tNLRU"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "baKkDJqjT",
									layoutId: "baKkDJqjT",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1mtvbqa-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"n4UZRv3pD-container"}
								nodeId={"n4UZRv3pD"}
								rendersWithMotion={true}
								scopeId={"trO8tNLRU"}
							>
								<Carousel
									align={"center"}
									ariaLabel={""}
									arrowObject={{
										arrowFill: "rgba(0, 0, 0, 0.2)",
										arrowPadding: 20,
										arrowRadius: 40,
										arrowSize: 40,
										showMouseControls: false,
									}}
									axis={true}
									borderRadius={0}
									fadeObject={{
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeTransition: {
											damping: 60,
											delay: 0,
											mass: 1,
											stiffness: 500,
											type: "spring",
										},
										fadeWidth: 25,
									}}
									gap={10}
									height={"100%"}
									id={"n4UZRv3pD"}
									layoutId={"n4UZRv3pD"}
									padding={17}
									paddingBottom={17}
									paddingLeft={17}
									paddingPerSide={false}
									paddingRight={17}
									paddingTop={17}
									progressObject={{
										dotsActiveOpacity: 1,
										dotsBackground: "rgba(0, 0, 0, 0)",
										dotsBlur: 5,
										dotsFill: "rgb(8, 8, 8)",
										dotsGap: 12,
										dotsInset: 10,
										dotSize: 10,
										dotsOpacity: 0.2,
										dotsPadding: 10,
										dotsRadius: 50,
										showProgressDots: true,
										showScrollbar: false,
									}}
									sizingObject={{
										heightInset: 0,
										heightRows: 2,
										heightType: "auto",
										widthColumns: 2,
										widthInset: 0,
										widthType: "auto",
									}}
									slots={[
										<ComponentViewportProvider height={227} width={"354px"}>
											<SmartComponentScopedContainer
												className={"framer-1xaoad7-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"Xntu_a497-container"}
												nodeId={"Xntu_a497"}
												rendersWithMotion={true}
												scopeId={"trO8tNLRU"}
											>
												{_jsx(stdin_default5, {
													height: "100%",
													id: "Xntu_a497",
													layoutId: "Xntu_a497",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={227} width={"354px"}>
											<SmartComponentScopedContainer
												className={"framer-1dz4d59-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"sAMHhIZuz-container"}
												nodeId={"sAMHhIZuz"}
												rendersWithMotion={true}
												scopeId={"trO8tNLRU"}
											>
												{_jsx(stdin_default4, {
													height: "100%",
													id: "sAMHhIZuz",
													layoutId: "sAMHhIZuz",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={227} width={"354px"}>
											<SmartComponentScopedContainer
												className={"framer-s4tjlr-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"tYyoCW9Tx-container"}
												nodeId={"tYyoCW9Tx"}
												rendersWithMotion={true}
												scopeId={"trO8tNLRU"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "tYyoCW9Tx",
													layoutId: "tYyoCW9Tx",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={227} width={"354px"}>
											<SmartComponentScopedContainer
												className={"framer-1xpfrf3-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"ygR8ok43V-container"}
												nodeId={"ygR8ok43V"}
												rendersWithMotion={true}
												scopeId={"trO8tNLRU"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													id: "ygR8ok43V",
													layoutId: "ygR8ok43V",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									snapObject={{
										fluid: false,
										snap: true,
										snapEdge: "center",
									}}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-C0sAA.framer-1pbnfro, .framer-C0sAA .framer-1pbnfro { display: block; }",
	".framer-C0sAA.framer-s2165h { height: 444px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 390px; }",
	".framer-C0sAA .framer-g4cswo-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-C0sAA .framer-1mtvbqa-container { bottom: 52px; flex: none; height: 270px; left: 0px; position: absolute; right: 0px; }",
	".framer-C0sAA .framer-1xaoad7-container, .framer-C0sAA .framer-1dz4d59-container, .framer-C0sAA .framer-s4tjlr-container, .framer-C0sAA .framer-1xpfrf3-container { height: 227px; position: relative; width: 354px; }",
];
var FramertrO8tNLRU = withCSS(Component, css, "framer-C0sAA");
var stdin_default6 = FramertrO8tNLRU;
FramertrO8tNLRU.displayName = "Reviews Mobile";
FramertrO8tNLRU.defaultProps = {
	height: 444,
	width: 390,
};
addFonts(
	FramertrO8tNLRU,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ReviewsBackgroundAndTextMobileFonts,
		...Review1MobileFonts,
		...Review2MobileFonts,
		...Review3MobileFonts,
		...Review4MobileFonts,
		...CarouselFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:reviews-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ReviewsMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var reviews_mobile_default = ComponentWithRoot;
export { reviews_mobile_default as default };
