// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Video } from "./chunks/chunk-2GQPUI7N.js";
import { Carousel } from "./chunks/chunk-ENEUJRQD.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:video-carousel-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kUd9aMggc4JMn1G7xe4N/Svn2L3F453SHE6m9RMXx/lQtAHBg3X.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var CarouselFonts = getFonts(Carousel);
var serializationHash = "framer-xEal8";
var variantClassNames = {
	GP7EoowZ6: "framer-v-1clusof",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "GP7EoowZ6",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1clusof",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"GP7EoowZ6"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-c8lic3"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"Kb5jKRJJl"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-font-size": "46px",
									}}
								>
									{"Smiles in motion,"}
								</motion.p>
								<motion.p
									style={{
										"--framer-font-size": "46px",
									}}
								>
									{"Capturing the moment"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-j5frz7-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"rdtHgbJI3-container"}
								nodeId={"rdtHgbJI3"}
								rendersWithMotion={true}
								scopeId={"lQtAHBg3X"}
							>
								<Carousel
									align={"center"}
									ariaLabel={""}
									arrowObject={{
										arrowFill: "rgba(0, 0, 0, 0.2)",
										arrowPadding: 20,
										arrowRadius: 40,
										arrowSize: 40,
										showMouseControls: false,
									}}
									axis={true}
									borderRadius={0}
									fadeObject={{
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeTransition: {
											damping: 60,
											delay: 0,
											mass: 1,
											stiffness: 500,
											type: "spring",
										},
										fadeWidth: 25,
									}}
									gap={24}
									height={"100%"}
									id={"rdtHgbJI3"}
									layoutId={"rdtHgbJI3"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									progressObject={{
										dotsActiveOpacity: 1,
										dotsBackground: "rgba(0, 0, 0, 0.2)",
										dotsBlur: 4,
										dotsFill: "rgb(255, 255, 255)",
										dotsGap: 10,
										dotsInset: 10,
										dotSize: 10,
										dotsOpacity: 0.5,
										dotsPadding: 10,
										dotsRadius: 50,
										showProgressDots: false,
										showScrollbar: true,
									}}
									sizingObject={{
										heightInset: 0,
										heightRows: 2,
										heightType: "auto",
										widthColumns: 2,
										widthInset: 0,
										widthType: "auto",
									}}
									slots={[
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1gl7hog-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"IxVr9uQK6-container"}
												nodeId={"IxVr9uQK6"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"IxVr9uQK6"}
													isMixedBorderRadius={false}
													layoutId={"IxVr9uQK6"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/Uqc4AFrkCfZLhexF3DhzJDEqE.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1rkouxi-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"yUclHagzG-container"}
												nodeId={"yUclHagzG"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"yUclHagzG"}
													isMixedBorderRadius={false}
													layoutId={"yUclHagzG"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/Dqhxth7XuUd4SF2brPt988v1HA.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-11biaf3-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"HO5IYKQ2V-container"}
												nodeId={"HO5IYKQ2V"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"HO5IYKQ2V"}
													isMixedBorderRadius={false}
													layoutId={"HO5IYKQ2V"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/i04zQ7gyfm9IgslV7Iwj0xVYU.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1cw2yei-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"e6lrEmgHX-container"}
												nodeId={"e6lrEmgHX"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"e6lrEmgHX"}
													isMixedBorderRadius={false}
													layoutId={"e6lrEmgHX"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/v1mGjxT9I7iYmv3rwzLoXNnI.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1it771u-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"myUYKNq5w-container"}
												nodeId={"myUYKNq5w"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"myUYKNq5w"}
													isMixedBorderRadius={false}
													layoutId={"myUYKNq5w"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/HC7Me0K6JysiDkpEUgzuqV96070.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1h1464c-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"Mxcv81Q2W-container"}
												nodeId={"Mxcv81Q2W"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"Mxcv81Q2W"}
													isMixedBorderRadius={false}
													layoutId={"Mxcv81Q2W"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/qM8KSJLFTcA3LyAqkugNAHDlw10.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-31ndm5-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"X_IYxQQ5H-container"}
												nodeId={"X_IYxQQ5H"}
												rendersWithMotion={true}
												scopeId={"lQtAHBg3X"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"X_IYxQQ5H"}
													isMixedBorderRadius={false}
													layoutId={"X_IYxQQ5H"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/A3VpTDdoFwmwipPlyXSM9wWZ7Co.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									snapObject={{
										fluid: false,
										snap: false,
										snapEdge: "center",
									}}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xEal8.framer-18d7e1j, .framer-xEal8 .framer-18d7e1j { display: block; }",
	".framer-xEal8.framer-1clusof { height: 873px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-xEal8 .framer-c8lic3 { flex: none; height: auto; left: 244px; position: absolute; top: 0px; white-space: pre; width: auto; }",
	".framer-xEal8 .framer-j5frz7-container { bottom: 0px; flex: none; height: 717px; position: absolute; right: 0px; width: 1456px; }",
	".framer-xEal8 .framer-1gl7hog-container, .framer-xEal8 .framer-31ndm5-container { height: 621px; position: relative; width: 401px; }",
	".framer-xEal8 .framer-1rkouxi-container, .framer-xEal8 .framer-1cw2yei-container, .framer-xEal8 .framer-1h1464c-container { height: 621px; position: relative; width: 404px; }",
	".framer-xEal8 .framer-11biaf3-container, .framer-xEal8 .framer-1it771u-container { height: 621px; position: relative; width: 400px; }",
];
var FramerlQtAHBg3X = withCSS(Component, css, "framer-xEal8");
var stdin_default = FramerlQtAHBg3X;
FramerlQtAHBg3X.displayName = "Video Carousel Desktop";
FramerlQtAHBg3X.defaultProps = {
	height: 873,
	width: 1700,
};
addFonts(
	FramerlQtAHBg3X,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
		...CarouselFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-carousel-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoCarouselDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var video_carousel_desktop_default = ComponentWithRoot;
export { video_carousel_desktop_default as default };
