// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-4DB5J72K.js";
import { Video } from "./chunks/chunk-2GQPUI7N.js";
import { Carousel } from "./chunks/chunk-ENEUJRQD.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:video-carousel-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zOwffDVc3ci0V8G68QUC/17kunxOXwC91VF18nnuh/I5unos58Y.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var CarouselFonts = getFonts(Carousel);
var SmilesInMotionMobileFonts = getFonts(stdin_default);
var serializationHash = "framer-v4mOJ";
var variantClassNames = {
	cMcm039vN: "framer-v-bmu2jk",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "cMcm039vN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-bmu2jk",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"cMcm039vN"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(51, 136, 255, 0)",
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-ta9msf-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"Ul7oYdsa3-container"}
								nodeId={"Ul7oYdsa3"}
								rendersWithMotion={true}
								scopeId={"I5unos58Y"}
							>
								<Carousel
									align={"center"}
									ariaLabel={""}
									arrowObject={{
										arrowFill: "rgba(0, 0, 0, 0.2)",
										arrowPadding: 20,
										arrowRadius: 40,
										arrowSize: 40,
										showMouseControls: false,
									}}
									axis={true}
									borderRadius={0}
									fadeObject={{
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeTransition: {
											damping: 60,
											delay: 0,
											mass: 1,
											stiffness: 500,
											type: "spring",
										},
										fadeWidth: 25,
									}}
									gap={24}
									height={"100%"}
									id={"Ul7oYdsa3"}
									layoutId={"Ul7oYdsa3"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									progressObject={{
										dotsActiveOpacity: 1,
										dotsBackground: "rgba(0, 0, 0, 0.2)",
										dotsBlur: 4,
										dotsFill: "rgb(255, 255, 255)",
										dotsGap: 10,
										dotsInset: 10,
										dotSize: 10,
										dotsOpacity: 0.5,
										dotsPadding: 10,
										dotsRadius: 50,
										showProgressDots: false,
										showScrollbar: true,
									}}
									sizingObject={{
										heightInset: 0,
										heightRows: 2,
										heightType: "auto",
										widthColumns: 2,
										widthInset: 0,
										widthType: "auto",
									}}
									slots={[
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-n3654a-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"IyDi5bghW-container"}
												nodeId={"IyDi5bghW"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"IyDi5bghW"}
													isMixedBorderRadius={false}
													layoutId={"IyDi5bghW"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/Uqc4AFrkCfZLhexF3DhzJDEqE.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-dppi2w-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"NNjhcacib-container"}
												nodeId={"NNjhcacib"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"NNjhcacib"}
													isMixedBorderRadius={false}
													layoutId={"NNjhcacib"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/Dqhxth7XuUd4SF2brPt988v1HA.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-v30lpk-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"tkZ8KWDhj-container"}
												nodeId={"tkZ8KWDhj"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"tkZ8KWDhj"}
													isMixedBorderRadius={false}
													layoutId={"tkZ8KWDhj"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/i04zQ7gyfm9IgslV7Iwj0xVYU.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-o5im0u-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"aaMGjwuX_-container"}
												nodeId={"aaMGjwuX_"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"aaMGjwuX_"}
													isMixedBorderRadius={false}
													layoutId={"aaMGjwuX_"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/v1mGjxT9I7iYmv3rwzLoXNnI.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1tcq2fu-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"SlKIoPzzv-container"}
												nodeId={"SlKIoPzzv"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"SlKIoPzzv"}
													isMixedBorderRadius={false}
													layoutId={"SlKIoPzzv"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/HC7Me0K6JysiDkpEUgzuqV96070.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1qiptn9-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"IE5OWRjyt-container"}
												nodeId={"IE5OWRjyt"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"IE5OWRjyt"}
													isMixedBorderRadius={false}
													layoutId={"IE5OWRjyt"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/qM8KSJLFTcA3LyAqkugNAHDlw10.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-14f8baa-container"}
												inComponentSlot={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"nMe4gC7Nw-container"}
												nodeId={"nMe4gC7Nw"}
												rendersWithMotion={true}
												scopeId={"I5unos58Y"}
											>
												<Video
													backgroundColor={"rgba(0, 0, 0, 0)"}
													borderRadius={20}
													bottomLeftRadius={20}
													bottomRightRadius={20}
													controls={false}
													height={"100%"}
													id={"nMe4gC7Nw"}
													isMixedBorderRadius={false}
													layoutId={"nMe4gC7Nw"}
													loop={true}
													muted={true}
													objectFit={"cover"}
													playing={true}
													posterEnabled={true}
													srcFile={
														"https://framerusercontent.com/assets/A3VpTDdoFwmwipPlyXSM9wWZ7Co.mp4"
													}
													srcType={"Upload"}
													srcUrl={
														"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
													}
													startTime={0}
													style={{
														height: "100%",
														width: "100%",
													}}
													topLeftRadius={20}
													topRightRadius={20}
													volume={25}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									snapObject={{
										fluid: false,
										snap: false,
										snapEdge: "center",
									}}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={77}
							width={"339px"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-tpipqv-container"}
								layoutDependency={layoutDependency}
								layoutId={"aigRiHlhb-container"}
								nodeId={"aigRiHlhb"}
								rendersWithMotion={true}
								scopeId={"I5unos58Y"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "aigRiHlhb",
									layoutId: "aigRiHlhb",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-v4mOJ.framer-1g3ojc8, .framer-v4mOJ .framer-1g3ojc8 { display: block; }",
	".framer-v4mOJ.framer-bmu2jk { height: 639px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 390px; }",
	".framer-v4mOJ .framer-ta9msf-container { bottom: 0px; flex: none; height: 549px; left: 0px; position: absolute; right: 0px; }",
	".framer-v4mOJ .framer-n3654a-container, .framer-v4mOJ .framer-v30lpk-container, .framer-v4mOJ .framer-1tcq2fu-container, .framer-v4mOJ .framer-14f8baa-container { height: 520px; position: relative; width: 282px; }",
	".framer-v4mOJ .framer-dppi2w-container, .framer-v4mOJ .framer-o5im0u-container, .framer-v4mOJ .framer-1qiptn9-container { height: 520px; position: relative; width: 283px; }",
	".framer-v4mOJ .framer-tpipqv-container { flex: none; height: 77px; left: calc(50.00000000000002% - 339px / 2); position: absolute; top: 0px; width: 339px; }",
];
var FramerI5unos58Y = withCSS(Component, css, "framer-v4mOJ");
var stdin_default2 = FramerI5unos58Y;
FramerI5unos58Y.displayName = "Video Carousel Mobile";
FramerI5unos58Y.defaultProps = {
	height: 639,
	width: 390,
};
addFonts(
	FramerI5unos58Y,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...VideoFonts,
		...CarouselFonts,
		...SmilesInMotionMobileFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-carousel-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoCarouselMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var video_carousel_mobile_default = ComponentWithRoot;
export { video_carousel_mobile_default as default };
