// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5fac0881a4f2bb24 "Patrick Dental (React Export)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-N5D5Y7KW.js";
import { routes } from "./chunks/chunk-LUVZXV62.js";

// virtual:your-smile-section-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/X8BShP5noVmMRhc58ZU4/EutzyC7LYdV2ceIUWVv4/qEM9f3116.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-KbSdM";
var variantClassNames = {
	kGDcUh7o8: "framer-v-1f2uk9",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "kGDcUh7o8",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1f2uk9",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"kGDcUh7o8"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-kp78r3"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"Xc1A_IsM_"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h6
									className={"framer-styles-preset-15xgadr"}
									data-styles-preset={"KNPSuSphB"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									{"Your smile's best friends, Our doctors"}
								</motion.h6>
							</React.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 2250,
								intrinsicWidth: 1633,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 959) -
										622,
								),
								pixelHeight: 4500,
								pixelWidth: 3266,
								sizes: "283px",
								src: "https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=4096&width=3266&height=4500",
								srcSet:
									"https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=1024&width=3266&height=4500 743w,https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=2048&width=3266&height=4500 1486w,https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?scale-down-to=4096&width=3266&height=4500 2972w,https://framerusercontent.com/images/w3FGIUO513xmKu1qQC8ATdz7pxU.jpg?width=3266&height=4500 3266w",
							}}
							className={"framer-1muziat"}
							data-framer-name={"Pexels-havanna-34457092"}
							layoutDependency={layoutDependency}
							layoutId={"KxdFXpg4L"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 2540,
								intrinsicWidth: 1695.5,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 959) -
										622,
								),
								pixelHeight: 5080,
								pixelWidth: 3391,
								sizes: "283px",
								src: "https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=4096&width=3391&height=5080",
								srcSet:
									"https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=1024&width=3391&height=5080 683w,https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=2048&width=3391&height=5080 1367w,https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?scale-down-to=4096&width=3391&height=5080 2734w,https://framerusercontent.com/images/znPAl6uVLIwEx3ISRP6VuiPRe2Y.jpg?width=3391&height=5080 3391w",
							}}
							className={"framer-bd6eok"}
							data-framer-name={"Pexels-pavel-danilyuk-8442615"}
							layoutDependency={layoutDependency}
							layoutId={"vbwrkjq6l"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 3e3,
								intrinsicWidth: 2e3,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 959) -
										622,
								),
								pixelHeight: 6e3,
								pixelWidth: 4e3,
								sizes: "283px",
								src: "https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=4096&width=4000&height=6000",
								srcSet:
									"https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=1024&width=4000&height=6000 682w,https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=2048&width=4000&height=6000 1365w,https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?scale-down-to=4096&width=4000&height=6000 2730w,https://framerusercontent.com/images/XRCmmMFFVMILqwbRQgKCXB1STk.jpg?width=4000&height=6000 4000w",
							}}
							className={"framer-r8wfnx"}
							data-framer-name={"Pexels-shkrabaanthony-5214995"}
							layoutDependency={layoutDependency}
							layoutId={"SQXClf4XN"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KbSdM.framer-7lubv5, .framer-KbSdM .framer-7lubv5 { display: block; }",
	".framer-KbSdM.framer-1f2uk9 { height: 959px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1700px; }",
	".framer-KbSdM .framer-kp78r3 { flex: none; height: 128px; left: 248px; position: absolute; top: 95px; white-space: pre-wrap; width: 553px; word-break: break-word; word-wrap: break-word; }",
	".framer-KbSdM .framer-1muziat { bottom: 189px; flex: none; height: 433px; left: 248px; overflow: visible; position: absolute; width: 283px; }",
	".framer-KbSdM .framer-bd6eok { bottom: 189px; flex: none; height: 433px; left: 608px; overflow: visible; position: absolute; width: 283px; }",
	".framer-KbSdM .framer-r8wfnx { bottom: 189px; flex: none; height: 433px; left: 955px; overflow: visible; position: absolute; width: 283px; }",
	...css,
];
var FramerqEM9f3116 = withCSS(Component, css2, "framer-KbSdM");
var stdin_default = FramerqEM9f3116;
FramerqEM9f3116.displayName = "Your Smile Section Desktop";
FramerqEM9f3116.defaultProps = {
	height: 959,
	width: 1700,
};
addFonts(
	FramerqEM9f3116,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:your-smile-section-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders YourSmileSectionDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5fac0881a4f2bb248231efb082dd5d2e0ecd3daaa2089f6807aa0138cff83410"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var your_smile_section_desktop_default = ComponentWithRoot;
export { your_smile_section_desktop_default as default };
